### PR TITLE
HttpURLConnection (#2976) - fix getResponseCode handled exceptions

### LINKED ISSUE #2976: urlconnection plugin: HttpURLConnection exceptions are captured also handled by the application.
## Describe the bug

Also the application handles all exceptions, especially expected ones the agent is reporting them to APM.

## Steps to reproduce

Simple Spring Boot Web application

```
@RequestMapping(method = RequestMethod.GET, path = "/ping")
public ResponseEntity<Object> ping() throws IOException {
    HttpURLConnection conn = (HttpURLConnection) new URL("https://google.de/404").openConnection();
    conn.setInstanceFollowRedirects(true);
    conn.setRequestMethod("GET");
    int code = conn.getResponseCode();
    System.out.println("Response Code: " + code);
    System.out.println("I reached the end without an exception!");
}
```
(Using Servlet with `RequestMapping` is just used to trigger the code inside a Spring Boot application).

gives following console output

```
Response Code: 404
I reached the end without an exception!
```

But the agent runs into https://github.com/elastic/apm-agent-java/blob/main/apm-agent-plugins/apm-urlconnection-plugin/src/main/java/co/elastic/apm/agent/urlconnection/HttpUrlConnectionInstrumentation.java#L132 and reports the exception to APM

Screenshot 2023-01-18 at 20 22 00

----

Different example using an url which response with 401, results into an `java.io.IOException` to be reported to APM, also 

```
Response Code: 401
I reached the end without an exception!
```

Screenshot 2023-01-18 at 20 37 26

## Expected behavior

Since everything runs as expected and exceptions are handled, there shouldn't be any exception reported towards APM (which as follow up results in an alert, if someone is creating alerts based on occurring exceptions)

## Debug logs

Log for the 404 example.

[reproducer.log](https://github.com/elastic/apm-agent-java/files/10449961/reproducer.log)

## Other remarks

We have observed same behaviour with AWS SDK S3 instrumentation, also there exceptions are captured also handled later on. Which means we have detected errors in APM, also the code handled and just works fine.

### PR DESCRIPTION
**Pull request by markush81**
## What does this PR do?
Fixes #2976 same way OTel has implemented its instrumentation of `HttpURLConnection`

## Checklist

- [ ] This is an enhancement of existing features, or a new feature in existing plugins
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] I have made corresponding changes to the documentation
- [x] This is a bugfix
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [x] I have added tests that would fail without this fix
- [ ] This is a new plugin
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [ ] My code follows the [style guidelines of this project](https://github.com/elastic/apm-agent-java/blob/main/CONTRIBUTING.md#java-language-formatting-guidelines)
  - [ ] I have made corresponding changes to the documentation
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/main/CONTRIBUTING.md#testing) pass locally with my changes
  - [ ] I have updated [supported-technologies.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/docs/supported-technologies.asciidoc)
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] Added an instrumentation plugin? Describe how you made sure that old, non-supported versions are not instrumented by accident.
- [ ] This is something else
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)

### CODE REVIEW

**Comment by eyalkoren** [comment]
@markush81 thanks for taking a shot on this! 🙏 
Please see my last [comment](https://github.com/elastic/apm-agent-java/issues/2976#issuecomment-1437227531) on the original issue. It explains how we think it would be best to approach this.
If you want to implement this yourself, we will be happy to assist and review. Otherwise, if you don't mind and agree that this approach is preferable, we can implement that.
Please let us know.

File: apm-agent-plugins/apm-urlconnection-plugin/src/test/java/co/elastic/apm/agent/urlconnection/HttpUrlConnectionInstrumentationTest.java [hunk 1]
```diff
@@ -121,4 +121,27 @@ public void testFakeReuse() throws Exception {
...
+
+    @Test
+    public void testGetResponseWithHandledException() throws Exception {
+        final HttpURLConnection urlConnection = (HttpURLConnection) new URL(getBaseUrl() + "/non-existent").openConnection();
+        urlConnection.getResponseCode();
+        urlConnection.disconnect();
+
+        verifyHttpSpan("localhost", "/non-existent", 404);
+        assertThat(reporter.getErrors()).isEmpty();
+    }
```
Comment (eyalkoren) [inline apm-agent-plugins/apm-urlconnection-plugin/src/test/java/co/elastic/apm/agent/urlconnection/HttpUrlConnectionInstrumentationTest.java:145]: Please add a test for the same URL only using `getInputStream()` (or even better- use `performGet()`) instead of `getResponseCode()` and verifying the expected behavior - `assertThat(reporter.getErrors()).hasSize(1)`

File: CHANGELOG.asciidoc [hunk 2]
```diff
@@ -38,6 +38,7 @@ communication - {pull}2996[#2996]
 * Fix for inferred spans where the parent id was also a child id - {pull}2686[#2686]
 * Fix context propagation for async 7.x and 8.x Elasticsearch clients - {pull}3015[#3015]
 * Fix exceptions filtering based on <<config-ignore-exceptions>> when those are <<config-unnest-exceptions, nested>> - {pull}3025[#3025]
+* Fix for `HttpUrlConnection.getResponseCode` capturing an exception, also internally already handled - {pull}3024[#3024]
```
Comment (eyalkoren) [inline CHANGELOG.asciidoc:41]:
```suggestion
* Fix usage of `HttpUrlConnection.getResponseCode()` causing an error event due to exception capturing, even when it is internally handled - {pull}3024[#3024]
```

**Review by eyalkoren — COMMENTED** [review]
Looks good! Thanks!
Please add the requested test to fully verify our intentions are addressed and maintained.

File: apm-agent-plugins/apm-urlconnection-plugin/src/test/java/co/elastic/apm/agent/urlconnection/HttpUrlConnectionInstrumentationTest.java [hunk 3]
```diff
@@ -121,4 +121,27 @@ public void testFakeReuse() throws Exception {
...
+    public void testGetResponseCodeWithUnhandledException() {
+        try {
+            final HttpURLConnection urlConnection = (HttpURLConnection) new URL("http://unknown").openConnection();
+            urlConnection.getResponseCode();
+            urlConnection.disconnect();
+        } catch (Exception e) {
+            // intentionally ignored
+        }
+
+        assertThat(reporter.getErrors()).hasSize(1);
```
Comment (eyalkoren) [inline apm-agent-plugins/apm-urlconnection-plugin/src/test/java/co/elastic/apm/agent/urlconnection/HttpUrlConnectionInstrumentationTest.java:134]:
```suggestion
        assertThat(reporter.getErrors()).hasSize(1);
        
        Assertions.assertThat(reporter.getFirstSpan(500)).isNotNull();
        assertThat(reporter.getSpans()).hasSize(1);
        Span span = reporter.getSpans().get(0);
        assertThat(span.getNameAsString()).isEqualTo("GET unknown");
        Http http = span.getContext().getHttp();
        assertThat(http.getStatusCode()).isEqualTo(0);
        assertThat(http.getUrl().toString()).isEqualTo("http://unknown");
```

Comment (markush81) [reply apm-agent-plugins/apm-urlconnection-plugin/src/test/java/co/elastic/apm/agent/urlconnection/HttpUrlConnectionInstrumentationTest.java:136]: adjusted

File: apm-agent-plugins/apm-urlconnection-plugin/src/test/java/co/elastic/apm/agent/urlconnection/HttpUrlConnectionInstrumentationTest.java (hunk 1 above)
Comment (markush81) [reply apm-agent-plugins/apm-urlconnection-plugin/src/test/java/co/elastic/apm/agent/urlconnection/HttpUrlConnectionInstrumentationTest.java:157]: added, but kind like redundant to `co.elastic.apm.agent.httpclient.AbstractHttpClientInstrumentationTest#testNonExistingHttpCall` except for the additional assert. So i am not sure if changing the mentioned test, would also be an option.

**Review by eyalkoren — APPROVED** [review]
👍 🙏

File: apm-agent-plugins/apm-urlconnection-plugin/src/test/java/co/elastic/apm/agent/urlconnection/HttpUrlConnectionInstrumentationTest.java (hunk 1 above)
Comment (eyalkoren) [reply apm-agent-plugins/apm-urlconnection-plugin/src/test/java/co/elastic/apm/agent/urlconnection/HttpUrlConnectionInstrumentationTest.java:157]: The additional assertion (for an error being captured) is exactly what makes it non-redundant, it is what verifies this codes does what we intend it does.
And changing the mentioned test is not preferable as this is a very specific behavior for `HttpUrlConnection` instrumentation and only when using `getInputStream`. Other clients do not report errors in such 404 requests.

Comment (markush81) [reply apm-agent-plugins/apm-urlconnection-plugin/src/test/java/co/elastic/apm/agent/urlconnection/HttpUrlConnectionInstrumentationTest.java:157]: > And changing the mentioned test is not preferable as this is a very specific behavior for `HttpUrlConnection` instrumentation and only when using `getInputStream`. Other clients do not report errors in such 404 requests.

True, that makes sense then.

**Comment by markush81** [comment]
run elasticsearch-ci/docs

**Review by jackshirazi — APPROVED** [review]
Great work, thanks!
