### PR TITLE
JAX-RS transaction name should be based on first annotated method

### LINKED ISSUE #1062: Jax-RS Transaction name gets overriden when calling another Jax-RS
When the implementation of a JAX-RS service calls another Method that exposes a JAX-RS service, the name of the transaction is overriden to the name of the second method, obscuring the original call.

## Steps to reproduce
Consider the following class:

```
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;

@Path("/test")
public class TestRestService {

    @GET
    public void methodA(){
        doSomeStuff()
        methodB();
        doMoreStuff()
    }

    @POST
    public void methodB(){
        doMethodBStuff()
    }

}


```
when methodA is called via HTTP, the Transaction will be named "methodB" by APM. The call to methodA is obscured. This happens because calls to JAX-RS endpoint rename the transaction even if the method is not the entry point to the transaction.

## Expected behavior
I would expec the APM-Transacton that gets traced when calling methodA via REST to be called "TestRestService#methodA" even if methodB is called inside the transaction.

## Sugestion
in #748 a priority system for overriding transaction names was introduced, but names with the same NamePriority as the current name can still override the current name. Maybe this could be changed to only higher priority? Just a thought.

### PR DESCRIPTION
**Pull request by eyalkoren**
## What does this PR do?

Introduce new internal API that allows setting a span name with the same priority.

## Checklist

- [x] My code follows the [style guidelines of this project](CONTRIBUTING.md#java-language-formatting-guidelines)
- [x] I have rebased my changes on top of the latest master branch

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#testing) pass locally with my changes

- [x] I have updated [CHANGELOG.asciidoc](CHANGELOG.asciidoc)

## Related issues

Closes #1062 

## Use cases

JAX-RS-annotated method delegating to another JAX-RS-annotated method - since it is the same plugin (and instrumentation), both attempt to set the name with the same priority, but we prefer the first, rather than the second.

### CODE REVIEW

File: apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/AbstractSpan.java [hunk 1]
```diff
@@ -164,7 +164,22 @@ public StringBuilder getNameForSerialization() {
...
+    }
+
+    /**
+     * Resets and returns the name {@link StringBuilder} if one of the following applies:
+     *  1.  the provided priority is {@code >} {@link #namePriority}
+     *  2.  the provided priority is {@code ==} {@link #namePriority} AND `overrideIfSamePriority` is `true`
+     * Otherwise, returns {@code null}
+     *
+     * @param namePriority the priority for the name. See also the {@code AbstractSpan#PRIO_*} constants.
+     * @return the name {@link StringBuilder} if the provided priority is {@code >=} {@link #namePriority}, {@code null} otherwise.
```
Comment (eyalkoren) [inline apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/AbstractSpan.java]: Note to self - adjust this comment and add description for the second parameter (copy + pasta)
