### PR TITLE
Instrumenting DB2 driver Statement classes based on package name

### LINKED ISSUE #925: DB2's prepared statement are not traced (jdbc)
**Describe the bug**
DB2's prepared statements are not traced. Agent does does instrument classes correctly.

**To Reproduce**
1. Include DB2 driver with project
2. Create a connection
3. Create a prepared statement
4. Execute prepared statement
5. Verify result from logs

**Expected behavior**
DB2's prepared statements are traced

**Debug logs**
-- Not required ---

**Cause**
Following condition in StatementInstrumentation excludes PreparedStatement implementation:

    @Override
    public ElementMatcher<? super NamedElement> getTypeMatcherPreFilter() {
        return nameContains("Statement");
    }

Ibm's PreparedStatement class is named as: com.ibm.db2.jcc.am.k4 (which violates all Java naming conventions). This obviously does not meet the expectation of class including Statement in its' name.

**Resolution (suggestion)**
Considering IBM is not following expected naming pattern and considering that there are certainly more issues than the one I encountered with Prepared Statements, it might make sense to add a condition that matches package for IBM's implementation. Assuming that name is fully qualified name with a package, condition should be: nameContains("Statement").or(nameContains("com.ibm.db2.jcc")) .

### PR DESCRIPTION
**Pull request by eyalkoren**
Closes #925 

### Checklist

- [x] Implement code
- [ ] Add tests (not yet, hopefully extending the IT for that)
- [x] Update [CHANGELOG.md](CHANGELOG.md)

### CODE REVIEW

File: apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/StatementInstrumentation.java [hunk 1]
```diff
@@ -76,7 +76,8 @@
 
     @Override
     public ElementMatcher<? super NamedElement> getTypeMatcherPreFilter() {
-        return nameContains("Statement");
+        // DB2 driver does not call its Statements statements.
+        return nameContains("Statement").or(nameStartsWith("com.ibm.db2.jcc"));
```
Comment (felixbarny) [inline apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/StatementInstrumentation.java]: Maybe just checking if the name contains `Connection` could be more generic? Both is fine to me, I leave up to you 🙂 

```suggestion
        return nameContains("Statement").or(nameContains("Connection"));
```

Comment (eyalkoren) [reply apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/StatementInstrumentation.java]: The user reported what we missed is called `com.ibm.db2.jcc.am.k4`

**Comment by eyalkoren** [comment]
Merging., deferring tests to a later stage. User verified this fixes the problem reported.
