### PR TITLE
Instrument Logger#error(String, Throwable)

### LINKED ISSUE #794: Logging frameworks integration - instrument for capturing error events
Instrument APIs such as `org.slf4j.Logger#error(Throwable)` and `java.util.logging.Logger#log(Level, Throwable)` and `captureException` through the currently active span.

### PR DESCRIPTION
**Pull request by kananindzya**
### Checklist

closes elastic/apm-agent-java#794 
- [x] Implement code
- [x] Add tests
- [ ] Update documentation
- [x] Update [CHANGELOG.md](CHANGELOG.md)
- [x] Update [supported-technologies.asciidoc](docs/supported-technologies.asciidoc)
- [ ] Added an API method or config option? Document in which version this will be introduced.

### CODE REVIEW

**Comment by kananindzya** [comment]
hi @eyalkoren , I try to instrument 
```
java.util.logging.Logger#log(Level level, String msg, Throwable thrown) 
```
but instrumentation doesn't work. Then I tried to instrument 
```
java.util.logging.LogRecord#setThrown(Throwable thrown)
```
Here, too, instrumentation doesn't work.

With slf4j everything is fine

**Comment by kananindzya** [comment]
> I don't think we need java.util.logging instrumentation in the first run, so just remove it if it's not working.
> 
> Please re-structure the unit tests to not use the Spring testing setup. That only seems to add unnecessary complexity. Or am I missing something?

fixed

File: apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/Slf4jLoggingInstrumentationTest.java [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+ * software distributed under the License is distributed on an
+ * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+ * KIND, either express or implied.  See the License for the
+ * specific language governing permissions and limitations
+ * under the License.
+ * #L%
+ */
+package co.elastic.apm.agent.error.logging;
+
+import org.junit.Test;
```
Comment (felixbarny) [inline apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/Slf4jLoggingInstrumentationTest.java]: Use Junit 5 (Jupiter)

File: apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/Slf4jLoggingInstrumentationTest.java [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+public class Slf4jLoggingInstrumentationTest extends AbstractErrorLoggingInstrumentationTest {
+
+    private static final Logger logger = LoggerFactory.getLogger(Slf4jLoggingInstrumentationTest.class);
+
+    @Test
+    public void captureException() {
+        try {
+            throw new RuntimeException("some business exception");
+        } catch (Exception e) {
+            logger.error("exception captured", e);
```
Comment (felixbarny) [inline apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/Slf4jLoggingInstrumentationTest.java]:
```suggestion
            logger.error("exception captured", new RuntimeException("some business exception"));
```

File: apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/Slf4jLoggingInstrumentationTest.java [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+public class Slf4jLoggingInstrumentationTest extends AbstractErrorLoggingInstrumentationTest {
+
+    private static final Logger logger = LoggerFactory.getLogger(Slf4jLoggingInstrumentationTest.class);
+
+    @Test
+    public void captureException() {
+        try {
```
Comment (felixbarny) [inline apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/Slf4jLoggingInstrumentationTest.java]: remove try-catch clause

File: apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/AbstractErrorLoggingInstrumentationTest.java [hunk 4]
```diff
@@ -0,0 +1,93 @@
...
+
+import co.elastic.apm.agent.MockReporter;
+import co.elastic.apm.agent.bci.ElasticApmAgent;
+import co.elastic.apm.agent.configuration.SpyConfiguration;
+import co.elastic.apm.agent.impl.ElasticApmTracer;
+import co.elastic.apm.agent.impl.ElasticApmTracerBuilder;
+import co.elastic.apm.agent.impl.transaction.TraceContext;
+import co.elastic.apm.agent.impl.transaction.Transaction;
+import net.bytebuddy.agent.ByteBuddyAgent;
+import org.junit.After;
```
Comment (felixbarny) [inline apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/AbstractErrorLoggingInstrumentationTest.java]: Only use Junit Jupiter annotations

File: apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/Slf4jLoggingInstrumentationTest.java (hunk 1 above)
Comment (kananindzya) [reply apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/Slf4jLoggingInstrumentationTest.java]: removed

File: apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/Slf4jLoggingInstrumentationTest.java (hunk 2 above)
Comment (kananindzya) [reply apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/Slf4jLoggingInstrumentationTest.java]: fixed

File: apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/Slf4jLoggingInstrumentationTest.java (hunk 3 above)
Comment (kananindzya) [reply apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/Slf4jLoggingInstrumentationTest.java]: removed

File: apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/AbstractErrorLoggingInstrumentationTest.java (hunk 4 above)
Comment (kananindzya) [reply apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/AbstractErrorLoggingInstrumentationTest.java]: deleeted

**Comment by kananindzya** [comment]
> * Automatically captures exceptions for `logger.error("message", exception);` calls

added to changelog, updated supported-technologies

**Comment by felixbarny** [comment]
Jenkins test this please

File: CHANGELOG.md [hunk 5]
```diff
@@ -9,6 +9,7 @@
 ## Features
  * Supporting OpenTracing version 0.33 
  * Added annotation and meta-annotation matching support for `trace_methods`
+ * Automatically captures exceptions for `logger.error("message", exception);` calls
```
Comment (eyalkoren) [inline CHANGELOG.md]:
```suggestion
 * Automatically captures exceptions for `logger.error("message", exception)` calls
```

File: apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/AbstractErrorLoggingInstrumentationTest.java [hunk 6]
```diff
@@ -0,0 +1,85 @@
...
+import org.junit.jupiter.api.AfterAll;
+import org.junit.jupiter.api.AfterEach;
+import org.junit.jupiter.api.BeforeAll;
+import org.junit.jupiter.api.BeforeEach;
+
+import java.util.Arrays;
+
+import static org.junit.Assert.assertEquals;
+
+public class AbstractErrorLoggingInstrumentationTest {
```
Comment (eyalkoren) [inline apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/AbstractErrorLoggingInstrumentationTest.java]: Extend `AbstractInstrumentationTest` and you get the `tracer` and `reporter` for free and you won't even need to init the instrumentation manually, as the service-loader-like mechanism will load them automatically.

File: docs/supported-technologies.asciidoc [hunk 7]
```diff
@@ -290,6 +290,8 @@ NOTE: only classes from packages configured in <<config-application-packages>>
 |When <<config-enable-log-correlation>> is set to `true`,
  the agent will add a https://www.slf4j.org/api/org/slf4j/MDC.html[MDC] entry for `trace.id` and `transaction.id`.
  See the <<config-enable-log-correlation>> configuration option for more details.
+
+ Automatically <<api-span-capture-exception,captures exceptions>> for `logger.error("message", exception);` calls
```
Comment (eyalkoren) [inline docs/supported-technologies.asciidoc]:
```suggestion
 Automatically <<api-span-capture-exception,captures exceptions>> for `logger.error("message", exception)` calls (since 1.10.0)
```

File: apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/AbstractErrorLoggingInstrumentationTest.java (hunk 6 above)
Comment (kananindzya) [reply apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/AbstractErrorLoggingInstrumentationTest.java]: Extended from AbstractInstrumentationTest, but without initInstrumentation , 0  advices applied.

**Comment by kananindzya** [comment]
> @kananindzya thanks for the PR! Well done!
> 
> What was the problem with the instrumentation of `java.util.logging`? Was there some error during instrumentation or that the classes were not instrumented without an error?

I think that instrumentation excluded, because it's started with java.*(java.util.*):
```
[main] DEBUG co.elastic.apm.agent.configuration.StartupInfo - classes_excluded_from_instrumentation: 'java.*,com.sun.*,sun.*' (source: elasticapm.properties)
[main] DEBUG co.elastic.apm.agent.configuration.StartupInfo - application_packages: 'co.elastic.apm' (source: elasticapm.properties)
[main] DEBUG co.elastic.apm.agent.configuration.StartupInfo - log_level: 'DEBUG' (source: elasticapm.properties)
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Applying instrumentation co.elastic.apm.agent.error.logging.JavaUtilLoggingInstrumentation
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Applied 1 advices
```

**Comment by kananindzya** [comment]
> > @kananindzya thanks for the PR! Well done!
> > What was the problem with the instrumentation of `java.util.logging`? Was there some error during instrumentation or that the classes were not instrumented without an error?
> 
> I think that instrumentation excluded, because it's started with java.* (java.util.* ):
> 
> ```
> [main] DEBUG co.elastic.apm.agent.configuration.StartupInfo - classes_excluded_from_instrumentation: 'java.*,com.sun.*,sun.*' (source: elasticapm.properties)
> [main] DEBUG co.elastic.apm.agent.configuration.StartupInfo - application_packages: 'co.elastic.apm' (source: elasticapm.properties)
> [main] DEBUG co.elastic.apm.agent.configuration.StartupInfo - log_level: 'DEBUG' (source: elasticapm.properties)
> [main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Applying instrumentation co.elastic.apm.agent.error.logging.JavaUtilLoggingInstrumentation
> [main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Applied 1 advices
> ```

With instrumentation:
```
public class JavaUtilLoggingInstrumentation extends ElasticApmInstrumentation {

    @Override
    public Class<?> getAdviceClass() {
        return JavaUtlLoggingAdviceService.class;
    }

    public static class JavaUtlLoggingAdviceService {

        @Advice.OnMethodEnter(suppress = Throwable.class)
        public static void logThrown(@Advice.Argument(2) Throwable exception) {
            if (tracer == null || tracer.getActive() == null) {
                return;
            }
            tracer.getActive().captureException(exception);
        }
    }

    @Override
    public ElementMatcher<? super TypeDescription> getTypeMatcher() {
        return named("java.util.logging.Logger");
    }

    @Override
    public ElementMatcher<? super MethodDescription> getMethodMatcher() {
        return named("log")
            .and(takesArgument(0, named("java.util.logging.Level")))
            .and(takesArgument(1, named("java.lang.String")))
            .and(takesArgument(2, named("java.lang.Throwable")));
    }
```
[main] DEBUG co.elastic.apm.agent.impl.payload.SystemInfo - container ID is null
[main] INFO co.elastic.apm.agent.configuration.StartupInfo - Starting Elastic APM (unknown version) as JUnitStarter on Java 10.0.2 (Oracle Corporation) Linux 5.0.0-25-generic
[main] DEBUG co.elastic.apm.agent.configuration.StartupInfo - disable_instrumentations: '' (source: elasticapm.properties)
[main] DEBUG co.elastic.apm.agent.configuration.StartupInfo - classes_excluded_from_instrumentation: 'com.sun.*,sun.*' (source: elasticapm.properties)
[main] DEBUG co.elastic.apm.agent.configuration.StartupInfo - application_packages: 'co.elastic.apm' (source: elasticapm.properties)
[main] DEBUG co.elastic.apm.agent.configuration.StartupInfo - log_level: 'DEBUG' (source: elasticapm.properties)
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Applying instrumentation co.elastic.apm.agent.error.logging.JavaUtilLoggingInstrumentation
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Applied 1 advices
[main] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - increment references to '' 00-686446641fbd78e0c212a361d477053c-de557258194a5020-01 (49cf9028) (1)
[main] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - startTransaction '' 00-686446641fbd78e0c212a361d477053c-de557258194a5020-01 (49cf9028) {
[main] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - increment references to '' 00-686446641fbd78e0c212a361d477053c-de557258194a5020-01 (49cf9028) (2)
[main] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Activating '' 00-686446641fbd78e0c212a361d477053c-de557258194a5020-01 (49cf9028) on thread 1
Sep 02, 2019 11:43:38 AM co.elastic.apm.agent.error.logging.JavaUtilLoggingInstrumentationTest captureException
SEVERE: exception captured
java.lang.RuntimeException: some business exception
	at co.elastic.apm.agent.error.logging.JavaUtilLoggingInstrumentationTest.captureException(JavaUtilLoggingInstrumentationTest.java:14)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:628)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:184)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:180)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:127)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

[main] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Deactivating '' 00-686446641fbd78e0c212a361d477053c-de557258194a5020-01 (49cf9028) on thread 1
[main] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to '' 00-686446641fbd78e0c212a361d477053c-de557258194a5020-01 (49cf9028) (1)
[main] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - } endTransaction 'unnamed' 00-686446641fbd78e0c212a361d477053c-de557258194a5020-01 (49cf9028)

java.lang.AssertionError: expected:<1> but was:<0>
Expected :1
Actual   :0
 <Click to see difference>


	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at co.elastic.apm.agent.error.logging.AbstractErrorLoggingInstrumentationTest.verifyThatExceptionCaptured(AbstractErrorLoggingInstrumentationTest.java:74)
```

File: apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/AbstractErrorLoggingInstrumentationTest.java (hunk 6 above)
Comment (eyalkoren) [reply apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/AbstractErrorLoggingInstrumentationTest.java]: That's because you called the resource directory `META-INF.services`, instead of having a `service` dir nested in a `META-INF` dir

**Comment by kananindzya** [comment]
> In order to resume the PR:
> 
>     1. Please fix the resource dir structure and properly extend AbstractInstrumentationTest
> 
>     2. Please run `mvn clean test` so that we will get the new instrumentation groups into the documentation
> 
>     3. [Optional] Try to figure out why the `java.util.logging` is not working now - do you invoke the instrumented method in the test?
1. Added resources dir.  Can you elaborate on what you mean by properly?
```

abstract class AbstractErrorLoggingInstrumentationTest extends AbstractInstrumentationTest {

    @BeforeAll
    public static void beforeAll() {
        reporter = new MockReporter();
        config = SpyConfiguration.createSpyConfig();
        tracer = new ElasticApmTracerBuilder()
            .configurationRegistry(config)
            .reporter(reporter)
            .build();
        ElasticApmAgent.initInstrumentation(tracer, ByteBuddyAgent.install(), Arrays.asList(new Slf4jLoggingInstrumentation()));
    }
```

**Comment by kananindzya** [comment]
2. 

> In order to resume the PR:
> 
>     1. Please fix the resource dir structure and properly extend AbstractInstrumentationTest
> 
>     2. Please run `mvn clean test` so that we will get the new instrumentation groups into the documentation
> 
>     3. [Optional] Try to figure out why the `java.util.logging` is not working now - do you invoke the instrumented method in the test?

2. I run ```mvn clean test``` but the group was not added
image

**Comment by eyalkoren** [comment]
> Can you elaborate on what you mean by properly?

It means - remove the entire `beforeAll` method- these fields are initialized in the parent

> I run `mvn clean test` but the group was not added

I assume this should also be fixed once you fix the `META-INF/services` directories

**Comment by kananindzya** [comment]
> > Can you elaborate on what you mean by properly?
> 
> It means - remove the entire `beforeAll` method- these fields are initialized in the parent
> 
> > I run `mvn clean test` but the group was not added
> 
> I assume this should also be fixed once you fix the `META-INF/services` directories

fixed
