### PR TITLE
Restore PreparedStatement#executeUpdate instrumentation

### LINKED ISSUE #917: [Regression] Agent fails to create spans for DML SQL commands
The agent does not create spans for SQL DML commands (Insert, Update), probably due to #883
This is a regression in 1.11.0, it used to work fine in 1.10.0. 

See screenshots of the same execution flow:
1.10.0:
agent-1 10 0
1.11.0:
agent-1 11 0

### Enviro
Kibana 6.7.1
Elasticsearch 6.7.1
Apm-server 6.7.2

Wildfly 9.0.2
Hibernate 4.3.10
OpenJDK 8

### Debug logs
No errors / warnings in APM logs. If debug logs are needed I'll have to anonymize the 2MB file, ugh. Is there a specific part of the logs that could help instead of the entire file?

### PR DESCRIPTION
**Pull request by eyalkoren**
Fixes #917 

### Checklist

- [x] Implement code
- [x] Add tests
- [x] Update [CHANGELOG.md](CHANGELOG.md)

### CODE REVIEW

File: apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/agent/jdbc/AbstractJdbcInstrumentationTest.java [hunk 1]
```diff
@@ -195,6 +198,25 @@ private void testUpdate(boolean isLargeUpdate) throws SQLException {
         assertSpanRecorded(insert, false, 1);
     }
 
+    private void testPreparedStatementUpdate(boolean isLargeUpdate) throws SQLException {
+        final String insert = "INSERT INTO ELASTIC_APM (FOO, BAR) VALUES (42, 'TEST')";
+
+        PreparedStatement statement = connection.prepareStatement(insert);
+
+        if (isLargeUpdate) {
+            boolean supported = executePotentiallyUnsupportedFeature(() -> statement.executeLargeUpdate());
```
Comment (felixbarny) [inline apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/agent/jdbc/AbstractJdbcInstrumentationTest.java]: can be simplified with

```java
Assumptions.assumeTrue(executePotentiallyUnsupportedFeature(() -> statement.executeLargeUpdate()));
```

File: apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/agent/jdbc/AbstractJdbcInstrumentationTest.java [hunk 2]
```diff
@@ -195,6 +198,25 @@ private void testUpdate(boolean isLargeUpdate) throws SQLException {
         assertSpanRecorded(insert, false, 1);
     }
 
+    private void testPreparedStatementUpdate(boolean isLargeUpdate) throws SQLException {
+        final String insert = "INSERT INTO ELASTIC_APM (FOO, BAR) VALUES (42, 'TEST')";
```
Comment (felixbarny) [inline apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/agent/jdbc/AbstractJdbcInstrumentationTest.java]: this is not an update 🤔 
but it's just about testing `executeUpdate()` right?

Comment (eyalkoren) [reply apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/agent/jdbc/AbstractJdbcInstrumentationTest.java]: This API is for DML queries in general, not specific to updates
