### PR TITLE
Fix parent/child issues with inferred spans

### LINKED ISSUE #1112: Regular spans can't be a child of profiler-inferred spans
## Describe the bug
APM Timeline starts with DB spans and shows them at top, but as per the application execution Java spans should be shown first and then DB spans.

## Steps to reproduce
Attached screenshots of our application.

In the below screenshot the transaction starts with DB Span:

APM-SPAN Order Mismatch

Below screenshot shows Java Spans after DB spans:

Java Span Misorder2

## Expected behavior
Various spans hierarchy  (like JAVA, DB etc) should be as per the application execution flow in the APM timeline.

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

### PR DESCRIPTION
**Pull request by felixbarny**
Inferred spans can track a list of child or successor ids
With transitive reduction, the UI can then make regular spans a child of inferred spans

## What does this PR do?

closes #1112 

## Checklist

- [x] My code follows the [style guidelines of this project](CONTRIBUTING.md#java-language-formatting-guidelines)
- [x] I have rebased my changes on top of the latest master branch

- ~[ ] I have made corresponding changes to the documentation~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#testing) pass locally with my changes

- [ ] I have updated [CHANGELOG.asciidoc](CHANGELOG.asciidoc)
- ~[ ] I have updated [supported-technologies.asciidoc](docs/supported-technologies.asciidoc)~
- ~[ ] Added an API method or config option? Document in which version this will be introduced~
- ~[ ] Added an instrumentation plugin? How did you make sure that old, non-supported versions are not instrumented by accident?~

### CODE REVIEW

File: apm-agent-plugins/apm-profiling-plugin/src/main/java/co/elastic/apm/agent/profiler/CallTree.java [hunk 1]
```diff
@@ -391,6 +414,25 @@ public void resetState() {
         }
     }
 
+    public void addChildId(long id) {
+        if (childIds == null) {
+            childIds = new LongList();
```
Comment (eyalkoren) [inline apm-agent-plugins/apm-profiling-plugin/src/main/java/co/elastic/apm/agent/profiler/CallTree.java:419]: Doesn't worth pooling?

File: apm-agent-plugins/apm-profiling-plugin/src/test/java/co/elastic/apm/agent/profiler/CallTreeTest.java [hunk 2]
```diff
@@ -262,6 +265,30 @@ void testDectivationBeforeEnd() throws Exception {
...
+     *  [a          ]      [a          ]
+     *   [2   ]  [3]        [b    ] [3]   <- b is supposed to stealChildIdsFom(a)
+     *    [b   ]            [2   ]           however, it should only steal 2, not 3
+     */
+    @Test
+    void testDectivationBeforeEnd2() throws Exception {
+        assertCallTree(new String[]{
+            "   bbbb b      ",
+            " a aaaa aa a a ",
+            "1 2    2  3 3 1"
```
Comment (eyalkoren) [inline apm-agent-plugins/apm-profiling-plugin/src/test/java/co/elastic/apm/agent/profiler/CallTreeTest.java:279]:
```suggestion
            "   bbbb b      ",
            " a aaaa a a a ",
            "1 2    2 3 3 1"
```
Just to make sure that one measurement is enough

File: apm-agent-plugins/apm-profiling-plugin/src/main/java/co/elastic/apm/agent/profiler/CallTree.java (hunk 1 above)
Comment (felixbarny) [reply apm-agent-plugins/apm-profiling-plugin/src/main/java/co/elastic/apm/agent/profiler/CallTree.java:419]: Not really. Lists are quite tricky to pool as they can have vastly different sizes. The danger is that over time, all lists in the pool will be quite large even though there are only few that actually contain a lot of elements.
Judging from the benchmarks, the allocations caused by the inferred spans processing increase by 10%. That seems reasonable and it's definitely not the major source of allocations.

File: apm-agent-plugins/apm-profiling-plugin/src/test/java/co/elastic/apm/agent/profiler/CallTreeTest.java (hunk 2 above)
Comment (felixbarny) [reply apm-agent-plugins/apm-profiling-plugin/src/test/java/co/elastic/apm/agent/profiler/CallTreeTest.java:279]: Hm, that doesn't work because `b` is still considered the top of the stack at the time `3` gets activated.

Comment (eyalkoren) [reply apm-agent-plugins/apm-profiling-plugin/src/test/java/co/elastic/apm/agent/profiler/CallTreeTest.java:279]: Why isn't that enough, if you know that activation of `3` happens after deactivation of `2` and you know that `b` cannot be a child of `3`?

Comment (felixbarny) [reply apm-agent-plugins/apm-profiling-plugin/src/test/java/co/elastic/apm/agent/profiler/CallTreeTest.java:279]: Because of situations like these:

```
 aa  aa 
1  22  1
```

We have to add each activation to the `childIds` of the current top of the stack.

However, it least to errors in situations like these:
```
 bbb      
 aaa aa a 
1   2  2 1
```

As 2 is falsely declared a child of b when it's actually a child of a. Currently not sure how to fix it without introducing regressions.

Comment (felixbarny) [reply apm-agent-plugins/apm-profiling-plugin/src/test/java/co/elastic/apm/agent/profiler/CallTreeTest.java]: I think I've managed to fix it

File: apm-agent-plugins/apm-profiling-plugin/src/test/java/co/elastic/apm/agent/profiler/CallTreeTest.java [hunk 3]
```diff
@@ -266,29 +272,181 @@ void testDeactivationBeforeEnd() throws Exception {
...
+     *    [b   ]           [2   ]          however, it should only steal 2, not 3
      */
     @Test
     void testDectivationBeforeEnd2() throws Exception {
         assertCallTree(new String[]{
-            "   bbbb b      ",
-            " a aaaa aa a a ",
-            "1 2    2  3 3 1"
+            "   bbbb b     ",
+            " a aaaa a a a ",
```
Comment (eyalkoren) [inline apm-agent-plugins/apm-profiling-plugin/src/test/java/co/elastic/apm/agent/profiler/CallTreeTest.java:284]: 💪

File: apm-agent-plugins/apm-profiling-plugin/src/test/java/co/elastic/apm/agent/profiler/CallTreeTest.java [hunk 4]
```diff
@@ -266,29 +272,181 @@ void testDeactivationBeforeEnd() throws Exception {
...
+            "1    23   32 1"
+        }, new Object[][]{
+            {"a", 8},
+            {"  b", 3},
+            {"  c", 3},
+        }, new Object[][]{
+            {"1", 13},
+            {"  a", 11},
+            {"    b", 2},
+            {"  2", 6},
```
Comment (eyalkoren) [inline apm-agent-plugins/apm-profiling-plugin/src/test/java/co/elastic/apm/agent/profiler/CallTreeTest.java:394]: How come `2` is not a child of `a`?

Comment (felixbarny) [reply apm-agent-plugins/apm-profiling-plugin/src/test/java/co/elastic/apm/agent/profiler/CallTreeTest.java:394]: Wow, good catch! From now on, I call you the eagle eye. Or maybe Eyeal 🤔 

Submitting fix shortly that searches for common ancestors, instead of always adding the child_ids on the top of the stack

File: apm-agent-plugins/apm-profiling-plugin/src/test/java/co/elastic/apm/agent/profiler/CallTreeTest.java [hunk 5]
```diff
@@ -262,6 +271,210 @@ void testDectivationBeforeEnd() throws Exception {
...
+            {"    b",     2},
+            {"    2",     6},
+            {"      3",   4},
+            {"        c", 2}
+        });
+
+        // this is empty but not null because a has stolen the child ids from b
+        assertThat(spans.get("b").getChildIds().getSize()).isEqualTo(0);
+        assertThat(spans.get("c").getChildIds()).isNull();
+        // has both 2 and 3 as child_ids, even though only 2 is a direct child
```
Comment (felixbarny) [inline apm-agent-plugins/apm-profiling-plugin/src/test/java/co/elastic/apm/agent/profiler/CallTreeTest.java:402]: This might be problematic for the UI: https://github.com/elastic/kibana/issues/62952#issuecomment-624472852

Comment (felixbarny) [reply apm-agent-plugins/apm-profiling-plugin/src/test/java/co/elastic/apm/agent/profiler/CallTreeTest.java]: Fixed it
