### PR TITLE
Fixing default service name configuration

### LINKED ISSUE #1323: the service_name option of the core configuration not works
I run my application as the cmd `java -Delastic.apm.service_name=foo -jar foo.jar`, but the apllication.properties has an item `spring.application.name=bar`.

expected:  the apm agent will report the data with service.name = foo
But actually, it's bar, the service name has been replaced!

From ElasticApmTracer : 

`

    @Override
    public void overrideServiceNameForClassLoader(@Nullable ClassLoader classLoader, @Nullable String serviceName) {
        // overriding the service name for the bootstrap class loader is not an actual use-case
        // null may also mean we don't know about the initiating class loader
        if (classLoader == null
            || serviceName == null || serviceName.isEmpty()
            // if the service name is set explicitly, don't override it
            || !coreConfiguration.getServiceNameConfig().isDefault()) {
            return;
        }
        if (!serviceNameByClassLoader.containsKey(classLoader)) {
            serviceNameByClassLoader.putIfAbsent(classLoader, ServiceNameUtil.replaceDisallowedChars(serviceName));
        }
    }

`

and from ServiceNameUtil

`

    public static String getDefaultServiceName() {
        return getDefaultServiceName(System.getProperty("sun.java.command"));
    }

    static String getDefaultServiceName(@Nullable String sunJavaCommand) {
        String serviceName = parseSunJavaCommand(sunJavaCommand);
        if (serviceName != null) {
            serviceName = replaceDisallowedChars(serviceName);
            serviceName = serviceName.trim();
        }
        if (serviceName == null || serviceName.isEmpty()) {
            serviceName = "my-service";
        }
        return serviceName;
    }

`

Although the `elastic.apm.service_name` has been set by command line, but it do not work, because it is equals with default value, which from the system property `sun.java.command`.

### PR DESCRIPTION
**Pull request by eyalkoren**
## What does this PR do?
Fixes #1323 

## Checklist

- [ ] This is an enhancement of existing features, or a new feature in existing plugins
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] I have made corresponding changes to the documentation
- [x] This is a bugfix
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [x] I have added tests that would fail without this fix
- [ ] This is a new plugin
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [ ] My code follows the [style guidelines of this project](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#java-language-formatting-guidelines)
  - [ ] I have made corresponding changes to the documentation
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#testing) pass locally with my changes
  - [ ] I have updated [supported-technologies.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/docs/supported-technologies.asciidoc)
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] Added an instrumentation plugin? Describe how you made sure that old, non-supported versions are not instrumented by accident.
- [ ] This is something else
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)

### CODE REVIEW

**Comment by felixbarny** [comment]
What's the error condition here? Is it that the `spring.application.name` form `application.properties` is used instead of the configured `service_name` in case it is the same as the one derived from the name of the jar (`sun.java.command`)?

File: apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracer.java [hunk 1]
```diff
@@ -696,7 +696,7 @@ public void overrideServiceNameForClassLoader(@Nullable ClassLoader classLoader,
         if (classLoader == null
             || serviceName == null || serviceName.isEmpty()
             // if the service name is set explicitly, don't override it
-            || !coreConfiguration.getServiceNameConfig().isDefault()) {
+            || coreConfiguration.getServiceNameConfig().getUsedKey() != null) {
```
Comment (felixbarny) [inline apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracer.java:699]: neat!

**Comment by eyalkoren** [comment]
> What's the error condition here? Is it that the spring.application.name form application.properties is used instead of the configured service_name in case it is the same as the one derived from the name of the jar (sun.java.command)?

Yes, the test I added fails without the fix
