### PR TITLE
classloader check on global tracer init

### LINKED ISSUE #1555: Detect when agent is added in application classpath
Agent is required to be loaded in the `bootstrap` classloader to ensure proper visibility of agent classes to the instrumented classes.

In practice, it's quite common that some setup issues trigger `ClassNotFoundException` with agent classes. This happens for example with some OSGi classloaders that do not delegate to `bootstrap` classloader unless they are configured to do so.

Given `ClassNotFoundException` symptom is often associated to `add an extra missing jar to your classpath` in an almost Pavlovian way to every Java developer, it's quite common that users try to add the agent jar to application classpath.

However, as agent jar is not a regular jar, this will cause more trouble than the initial issue, as some agent classes will be loaded in the wrong classloader and will create hard to diagnose issues.

Thus, we should be able to detect such setup errors at runtime and warn end-user of such issues with a proper error message. Optionally, we could even make the agent self-disable.

Heuristic / Implementation proposal(s)
- instrumentation with an empty advice that matches on `ElasticApmAgent` and checks whether the class loader is neither the System CL nor the bootstrap CL.

### PR DESCRIPTION
**Pull request by SylvainJuge**
## What does this PR do?

Fixes #1555

Ensures that the agent will throw an exception when agent has been added to application dependencies (and thus that the agent is not being loaded from the bootstrap classloader). While exception will likely break the application, it makes it obvious that there is a setup issue that requires immediate action.

## Checklist

- [x] This is something else
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)

## Implementation checklist
- [x] ensure tests run properly with this extra check
- [x] manual testing with sample application with packaged agent as dependency using `Class.forname(...)` that tries to load agent `GlobalTracer`.

### CODE REVIEW

File: apm-agent-core/src/main/java/co/elastic/apm/agent/impl/GlobalTracer.java [hunk 1]
```diff
@@ -54,17 +63,52 @@ public static ElasticApmTracer requireTracerImpl() {
...
+                Manifest manifest = new Manifest(resources.nextElement().openStream());
+                Attributes attributes = manifest.getMainAttributes();
+                String preMain = attributes.getValue("Premain-Class");
+                if (preMain != null && preMain.startsWith("co.elastic.apm.agent")) {
+                    return false;
+                }
+            }
+        } catch (IOException e) {
+            throw new IllegalStateException(e);
+        }
```
Comment (eyalkoren) [inline apm-agent-core/src/main/java/co/elastic/apm/agent/impl/GlobalTracer.java:97]: [minor]

Maybe you can reuse https://github.com/elastic/apm-agent-java/blob/f9267ff7fc7df619cb2272b8790fde618055c8f6/apm-agent-core/src/main/java/co/elastic/apm/agent/util/VersionUtils.java#L105

Or even just do something like https://github.com/elastic/apm-agent-java/blob/f9267ff7fc7df619cb2272b8790fde618055c8f6/apm-agent-premain/src/main/java/co/elastic/apm/agent/premain/AgentMain.java#L157 - we only want to see the class is coming from within a jar

File: apm-agent-core/src/main/java/co/elastic/apm/agent/impl/GlobalTracer.java [hunk 2]
```diff
@@ -54,17 +63,52 @@ public static ElasticApmTracer requireTracerImpl() {
...
     }
 
+    private static void checkClassloader() {
+        ClassLoader cl = GlobalTracer.class.getClassLoader();
+
+        if (classloaderCheck(cl)) {
+            return;
+        }
+
+        throw new IllegalStateException("Agent setup error: must be loaded in bootstap classloader, should not be included in application dependencies. Classloader : " + cl);
```
Comment (eyalkoren) [inline apm-agent-core/src/main/java/co/elastic/apm/agent/impl/GlobalTracer.java:73]: [proposal] I think this message should be very focused on how the user can fix it - no need to say anything about class loaders even, only that the agent seems to have been setup improperly, and it is likely referenced by the JVM or application classpath, or used as a dependency.

**Review by eyalkoren — APPROVED** [review]
Elegant solution!
Added two proposals for you to consider

File: apm-agent-core/src/main/java/co/elastic/apm/agent/impl/GlobalTracer.java (hunk 1 above)
Comment (SylvainJuge) [reply apm-agent-core/src/main/java/co/elastic/apm/agent/impl/GlobalTracer.java:111]: Very good idea, it's even simpler to check and does not require manifest parsing.

File: apm-agent-core/src/main/java/co/elastic/apm/agent/impl/GlobalTracer.java (hunk 2 above)
Comment (SylvainJuge) [reply apm-agent-core/src/main/java/co/elastic/apm/agent/impl/GlobalTracer.java]: Definitely agree here, the reason people tend to put this `.jar` on the classpath is because they have heard too much "put things on classpath" :-).

**Comment by SylvainJuge** [comment]
Actually just checking that the class file is packaged in a `.jar` is not enough, as the current state of PR makes tests fail with :

```
java.lang.ExceptionInInitializerError
Caused by: java.lang.IllegalStateException: Agent setup error: agent jar file "/var/lib/jenkins/workspace/_java_apm-agent-java-mbp_PR-2076/src/github.com/elastic/apm-agent-java/apm-agent-core/target/apm-agent-core-1.25.1-SNAPSHOT.jar"  likely referenced in JVM or application classpath
```

Thus I'll revert to the previous version (or add an extra condition to only apply this check when properly packaged as an agent).

**Comment by eyalkoren** [comment]
If the `GlobalTracer` is loaded from within the agent jar, wouldn't the other check also fail do to the presence of manifest?
