### PR TITLE
remove useless allocation in TraceState.copyOf()

### LINKED ISSUE #1503: Allocation rate increase after PR 1384
The https://github.com/elastic/apm-agent-java/pull/1384 PR introduced a performance regression for allocation rate, about extra 50 bytes per transactions are now allocated.

image

### PR DESCRIPTION
**Pull request by SylvainJuge**
## What does this PR do?

Fixes #1503 

## Checklist

- [x] This is a bugfix
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [x] ~I have added tests that would fail without this fix~ tested locally with async-profiler

### CODE REVIEW

**Review by eyalkoren — CHANGES_REQUESTED** [review]
Leaking a member of a pooled object to another pooled object is very problematic.

I think we should avoid adding the `header` field to the `tracestate` list (in `TraceState#set()`) and adjust the `TraceState#toTextHeader()` method (as well as the `TraceState.TextTracestateAppender#join()` method) to append it only when required.
`TraceState#copyFrom()` already takes care of copying the `header` value.

One additional thing to fix is resetting `header` in `TraceState#resetState`.

File: apm-agent-core/src/main/java/co/elastic/apm/agent/impl/sampling/ConstantSampler.java [hunk 1]
```diff
@@ -36,12 +37,15 @@
 
     private final boolean decision;
     private final double rate;
+
     private final String rateString;
```
Comment (eyalkoren) [inline apm-agent-core/src/main/java/co/elastic/apm/agent/impl/sampling/ConstantSampler.java:41]: We can remove this one I guess
```suggestion
```

File: apm-agent-core/src/main/java/co/elastic/apm/agent/impl/sampling/ConstantSampler.java [hunk 2]
```diff
@@ -36,12 +37,15 @@
...
+    private final String traceStateHeader;
 
     private ConstantSampler(boolean decision) {
         this.decision = decision;
-        rate = decision ? 1.0d : 0.0d;
-        rateString = Double.toString(rate);
+        this.rate = decision ? 1.0d : 0.0d;
+        this.rateString = Double.toString(rate);
```
Comment (eyalkoren) [inline apm-agent-core/src/main/java/co/elastic/apm/agent/impl/sampling/ConstantSampler.java:47]:
```suggestion
```

File: apm-agent-core/src/main/java/co/elastic/apm/agent/impl/sampling/ProbabilitySampler.java [hunk 3]
```diff
@@ -56,16 +56,16 @@
...
-        lowerBound = -higherBound;
+        this.higherBound = (long) (Long.MAX_VALUE * samplingRate);
+        this.lowerBound = -higherBound;
         this.sampleRate = samplingRate;
-        rateString = Double.toString(samplingRate);
+        this.traceStateHeader = TraceState.getHeaderValue(samplingRate);
     }
 
-    public static Sampler of(double samplingRate) {
+    public static Sampler of(double samplingRate) { // use 'Double' here
```
Comment (eyalkoren) [inline apm-agent-core/src/main/java/co/elastic/apm/agent/impl/sampling/ProbabilitySampler.java:68]: I didn't get this comment

File: apm-agent-core/src/main/java/co/elastic/apm/agent/impl/sampling/Sampler.java [hunk 4]
```diff
@@ -57,8 +57,10 @@
      */
     double getSampleRate();
 
+    // While header is not related to sampler itself, putting this here allows to reuse the same
+    // String instance as long as the sample rate does not change to minimize allocation
```
Comment (eyalkoren) [inline apm-agent-core/src/main/java/co/elastic/apm/agent/impl/sampling/Sampler.java:61]: 👍  Can be added to the javadoc

**Review by eyalkoren — APPROVED** [review]
LGTM.
Few minor comment.
