### PR TITLE
Fixing GlobalThreadLocal to use per-thread default values

### LINKED ISSUE #2117: `GlobalThreadLocal` uses constant default value
Instead, the constructor should be changed so that it receives a `Callable<T>` or a custom type (as we can't use `Supplier<T>`, `Function<Thread, T>` due to Java 7 compatibility).

Currently, there is an issue in the `co.elastic.apm.agent.okhttp.OkHttpClientHelper` which uses the same `StringBuilder` instance for every thread.

### PR DESCRIPTION
**Pull request by eyalkoren**
## What does this PR do?

Closes #2117 
## Checklist

- [x] This is a bugfix
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [x] I have added tests that would fail without this fix

### CODE REVIEW

File: apm-agent-plugin-sdk/src/test/java/co/elastic/apm/agent/sdk/state/GlobalThreadLocalTest.java [hunk 1]
```diff
@@ -20,12 +20,103 @@
...
-        threadLocal.set(null);
+        GlobalThreadLocal.get(GlobalThreadLocalTest.class, "setNullValueShouldNotThrow").set(null);
+    }
+
+    @Test
+    void testNonConstantDefaultValue() throws ExecutionException, InterruptedException {
+        final GlobalThreadLocal<Object> threadLocal = GlobalThreadLocal.get(
+            GlobalThreadLocalTest.class,
+            "testNonConstantDefaultValue",
+            new ObjectValueSupplier()
```
Comment (felixbarny) [inline apm-agent-plugin-sdk/src/test/java/co/elastic/apm/agent/sdk/state/GlobalThreadLocalTest.java:46]: [minor] may be replaced with lambda
```suggestion
            () -> new Object()
```

**Review by felixbarny — APPROVED** [review]
