### PR TITLE
Use emulated attach as fallback

### LINKED ISSUE #2383: com.sun.tools.attach.AttachNotSupportedException: Unable to get pid of LinuxThreads manager thread
Hello, 
i am trying de start a docker container but i get this error stack  : 

```
Exception in thread "main" java.lang.reflect.InvocationTargetExceptionj
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.IllegalStateException: Error during attachment using: co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@1b701da1
at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:639)
at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:299)
at co.elastic.apm.attach.ElasticApmAttacher.attach(ElasticApmAttacher.java:154)
at co.elastic.apm.attach.ElasticApmAttacher.attach(ElasticApmAttacher.java:140)
at co.elastic.apm.attach.ElasticApmAttacher.attach(ElasticApmAttacher.java:105)
at co.elastic.apm.attach.ElasticApmAttacher.attach(ElasticApmAttacher.java:58)
at org.autolab.gateway.AutolabGatewayApplication.main(AutolabGatewayApplication.java:19)
... 8 more
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at co.elastic.apm.attach.bytebuddy.agent.Attacher.install(Attacher.java:102)
at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:634)
... 14 more
Caused by: com.sun.tools.attach.AttachNotSupportedException: Unable to get pid of LinuxThreads manager thread
at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:86)
at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
... 20 more
```

ENV : 
Spring boot 
pom : 

```xml
    <properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<spring-cloud.version>Finchley.RC2</spring-cloud.version>
		<spring-security-jwt>1.0.9.RELEASE</spring-security-jwt>
		<maven.surefire.plugin>2.19.1</maven.surefire.plugin>
		<logstash.logback.version>4.11</logstash.logback.version>
		<elastic-apm.version>1.28.4</elastic-apm.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-config-server</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-config</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-hystrix</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-zuul</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-jwt</artifactId>
			<version>${spring-security-jwt}</version>
		</dependency>
		<dependency>
			<groupId>org.keycloak</groupId>
			<artifactId>keycloak-spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>net.logstash.logback</groupId>
			<artifactId>logstash-logback-encoder</artifactId>
			<version>${logstash.logback.version}</version>
		</dependency>
		<dependency>
			<groupId>co.elastic.apm</groupId>
			<artifactId>apm-agent-attach</artifactId>
			<version>${elastic-apm.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.keycloak.bom</groupId>
				<artifactId>keycloak-adapter-bom</artifactId>
				<version>13.0.1</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>${maven.surefire.plugin}</version>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>
```

DockerFIle : 

```
FROM openjdk:8-jdk-alpine
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} gateway.jar
ENTRYPOINT ["java","-Dspring.profiles.active=dev","-jar","/gateway.jar"]
```

main starter : 
```java
 @SpringBootApplication 
 @EnableZuulProxy 
 @EnableHystrix
 @EnableDiscoveryClient
 @EnableConfigurationProperties
public class AutolabGatewayApplication {

	public static void main(String[] args) {
		ElasticApmAttacher.attach();
		SpringApplication.run(AutolabGatewayApplication.class, args);
	}
}
```

### PR DESCRIPTION
**Pull request by SylvainJuge**
## What does this PR do?

Fixes #2383

It appears that some openjdk images do not behave as expected when using runtime attach.
- `openjdk:8-jdk-alpine` does not work and produce the stack trace below, the "native attach" is available as its a JDK, but there is no fallback to the emulated attach in this case
- `openjdk:8-jre-alpine` works, as a JRE is used only the "emulated attach" is available

One possible work-around is to add the `--init` argument to the `docker run` command, but that's not really convenient.
The agent already has a permanent work-around in the form of the "emulated attach" that already allows to use a JRE.

<details><summary>Stack trace</summary>
<p>

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.IllegalStateException: Error during attachment using: co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@5e91993f
        at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:639)
        at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:299)
        at co.elastic.apm.attach.ElasticApmAttacher.attach(ElasticApmAttacher.java:154)
        at co.elastic.apm.attach.ElasticApmAttacher.attach(ElasticApmAttacher.java:140)
        at co.elastic.apm.attach.ElasticApmAttacher.attach(ElasticApmAttacher.java:105)
        at co.elastic.apm.attach.ElasticApmAttacher.attach(ElasticApmAttacher.java:58)
        at com.example.springboot.Application.main(Application.java:16)
        ... 8 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at co.elastic.apm.attach.bytebuddy.agent.Attacher.install(Attacher.java:102)
        at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:634)
        ... 14 more
Caused by: com.sun.tools.attach.AttachNotSupportedException: Unable to get pid of LinuxThreads manager thread
        at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:86)
        at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
        ... 20 more
```

</p>
</details>

## Checklist

- [x] This is a bugfix
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [x] ~~I have added tests that would fail without this fix~~
  - [x] manually testing (and reproducing) the issue with a local application

### CODE REVIEW

File: apm-agent-attach/src/main/java/co/elastic/apm/attach/ElasticApmAttacher.java [hunk 1]
```diff
@@ -151,14 +151,34 @@ public static void attach(String pid, Map<String, String> configuration, File ag
...
+        } catch (RuntimeException e1) {
+            try {
+                ByteBuddyAgent.attach(agentJarFile, pid, agentArgs, ElasticAttachmentProvider.getFallback());
+            } catch (RuntimeException e2) {
+                // output the two exceptions for debugging
+                System.err.println("Unable to attach with fallback provider:");
+                e2.printStackTrace();
+
+                System.err.println("Unable to attach with regular provider:");
+                e1.printStackTrace();
```
Comment (SylvainJuge) [inline apm-agent-attach/src/main/java/co/elastic/apm/attach/ElasticApmAttacher.java:177]: [for reviewer] One major difference with the current implementation is that any failure during attachment won't prevent the application to start. While this might be desirable to fail more silently, it means that users are likely to not see any error unless they inspect their application standard output/logs.

File: apm-agent-attach/src/main/java/co/elastic/apm/attach/ElasticApmAttacher.java [hunk 2]
```diff
@@ -151,14 +151,34 @@ public static void attach(String pid, Map<String, String> configuration, File ag
...
-        ByteBuddyAgent.attach(agentJarFile, pid, agentArgs, ElasticAttachmentProvider.get());
+        attachWithFallback(agentJarFile, pid, agentArgs);
         if (tempFile != null) {
             if (!tempFile.delete()) {
                 tempFile.deleteOnExit();
             }
         }
     }
 
+    private static void attachWithFallback(File agentJarFile, String pid, String agentArgs) {
```
Comment (jackshirazi) [inline apm-agent-attach/src/main/java/co/elastic/apm/attach/ElasticApmAttacher.java:162]: do we have a test that shows the various attach failures?

Comment (SylvainJuge) [reply apm-agent-attach/src/main/java/co/elastic/apm/attach/ElasticApmAttacher.java:162]: No we don't, mostly because that depends on the JVM its running on.

An integration test with a few docker images could help us test it, but I'm not sure it's really worth for now as we only had a single issue here so far.

**Review by jackshirazi — APPROVED** [review]
nice
