### PR TITLE
Properly disable agent on startup

### LINKED ISSUE #1444: Configuration enabled=false ignored on self approache
## Description
When attach the agent via `ElasticApmAttacher.attach()` and having set `enabled=false` then agent is attached anyway. The `elasticapm.properties` file is loaded in `co.elastic.apm.attach.ElasticApmAttacher#attach(java.lang.String)` but it seems to be ignored.

 Given:
```java
@SpringBootApplication
public class DemoApplication {
        
        //not called by tests
	public static void main(String[] args) {
		ElasticApmAttacher.attach(); 
		SpringApplication.run(DemoApplication.class, args);
	}

}
```
Test:
```java
@SpringBootTest
class DemoApplicationTests {

	@Test
	void contextLoads() throws InterruptedException {
		ElasticApmAttacher.attach(); //just to illustrate 
		Thread.sleep(5000);
	}

}
```
with src/test/resources/elasticapm.properties
```
enabled=false
```

## Steps to reproduce
1. Use this config 'enabled=false' in elasticapm.properties
2. Then execute 'application or test'
3. See log output

## Expected behavior
When set `enabled=false` then nothing should be attached nor a apm server health check should be done.

## Debug logs
<details>
<summary>Click to expand</summary>

Application Log
```
/home/thomashaarbach/.jdks/openjdk-14/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:37959,suspend=y,server=n -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -agentpath:/tmp/libmemory_agent5.so= -Dfile.encoding=UTF-8 -classpath /home/thomashaarbach/Projekte/elastic-apm-test/target/classes:/home/thomashaarbach/.m2/repository/org/springframework/boot/spring-boot-starter-web/2.3.4.RELEASE/spring-boot-starter-web-2.3.4.RELEASE.jar:/home/thomashaarbach/.m2/repository/org/springframework/boot/spring-boot-starter/2.3.4.RELEASE/spring-boot-starter-2.3.4.RELEASE.jar:/home/thomashaarbach/.m2/repository/org/springframework/boot/spring-boot/2.3.4.RELEASE/spring-boot-2.3.4.RELEASE.jar:/home/thomashaarbach/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.3.4.RELEASE/spring-boot-autoconfigure-2.3.4.RELEASE.jar:/home/thomashaarbach/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.3.4.RELEASE/spring-boot-starter-logging-2.3.4.RELEASE.jar:/home/thomashaarbach/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar:/home/thomashaarbach/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar:/home/thomashaarbach/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.13.3/log4j-to-slf4j-2.13.3.jar:/home/thomashaarbach/.m2/repository/org/apache/logging/log4j/log4j-api/2.13.3/log4j-api-2.13.3.jar:/home/thomashaarbach/.m2/repository/org/slf4j/jul-to-slf4j/1.7.30/jul-to-slf4j-1.7.30.jar:/home/thomashaarbach/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar:/home/thomashaarbach/.m2/repository/org/yaml/snakeyaml/1.26/snakeyaml-1.26.jar:/home/thomashaarbach/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.3.4.RELEASE/spring-boot-starter-json-2.3.4.RELEASE.jar:/home/thomashaarbach/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.11.2/jackson-databind-2.11.2.jar:/home/thomashaarbach/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.11.2/jackson-annotations-2.11.2.jar:/home/thomashaarbach/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.11.2/jackson-core-2.11.2.jar:/home/thomashaarbach/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.11.2/jackson-datatype-jdk8-2.11.2.jar:/home/thomashaarbach/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.11.2/jackson-datatype-jsr310-2.11.2.jar:/home/thomashaarbach/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.11.2/jackson-module-parameter-names-2.11.2.jar:/home/thomashaarbach/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/2.3.4.RELEASE/spring-boot-starter-tomcat-2.3.4.RELEASE.jar:/home/thomashaarbach/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/9.0.38/tomcat-embed-core-9.0.38.jar:/home/thomashaarbach/.m2/repository/org/glassfish/jakarta.el/3.0.3/jakarta.el-3.0.3.jar:/home/thomashaarbach/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/9.0.38/tomcat-embed-websocket-9.0.38.jar:/home/thomashaarbach/.m2/repository/org/springframework/spring-web/5.2.9.RELEASE/spring-web-5.2.9.RELEASE.jar:/home/thomashaarbach/.m2/repository/org/springframework/spring-beans/5.2.9.RELEASE/spring-beans-5.2.9.RELEASE.jar:/home/thomashaarbach/.m2/repository/org/springframework/spring-webmvc/5.2.9.RELEASE/spring-webmvc-5.2.9.RELEASE.jar:/home/thomashaarbach/.m2/repository/org/springframework/spring-aop/5.2.9.RELEASE/spring-aop-5.2.9.RELEASE.jar:/home/thomashaarbach/.m2/repository/org/springframework/spring-context/5.2.9.RELEASE/spring-context-5.2.9.RELEASE.jar:/home/thomashaarbach/.m2/repository/org/springframework/spring-expression/5.2.9.RELEASE/spring-expression-5.2.9.RELEASE.jar:/home/thomashaarbach/.m2/repository/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar:/home/thomashaarbach/.m2/repository/org/springframework/spring-core/5.2.9.RELEASE/spring-core-5.2.9.RELEASE.jar:/home/thomashaarbach/.m2/repository/org/springframework/spring-jcl/5.2.9.RELEASE/spring-jcl-5.2.9.RELEASE.jar:/home/thomashaarbach/.m2/repository/co/elastic/apm/apm-agent-attach/1.18.1/apm-agent-attach-1.18.1.jar:/home/thomashaarbach/.m2/repository/net/java/dev/jna/jna/5.3.1/jna-5.3.1.jar:/home/thomashaarbach/.m2/repository/net/java/dev/jna/jna-platform/5.3.1/jna-platform-5.3.1.jar:/home/thomashaarbach/.m2/repository/co/elastic/apm/apm-agent-api/1.18.1/apm-agent-api-1.18.1.jar:/home/thomashaarbach/Tools/ideaIU-2018.3/lib/idea_rt.jar org.jstage.demo.DemoApplication
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Connected to the target VM, address: '127.0.0.1:37959', transport: 'socket'
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
_**2020-10-19 16:24:54,156 [Attach Listener] INFO  co.elastic.apm.agent.util.JmxUtils - Found JVM-specific OperatingSystemMXBean interface: com.sun.management.OperatingSystemMXBean
2020-10-19 16:24:54,174 [Attach Listener] INFO  co.elastic.apm.agent.configuration.StartupInfo - Starting Elastic APM 1.18.1 as DemoApplication on Java 14 Runtime version: 14+36-1461 VM version: 14+36-1461 (Oracle Corporation) Linux 5.8.15-201.fc32.x86_64
2020-10-19 16:24:54,174 [Attach Listener] WARN  co.elastic.apm.agent.configuration.StartupInfo - To enable all features and decrease startup time, please configure application_packages
2020-10-19 16:24:54,179 [elastic-apm-server-healthcheck] WARN  co.elastic.apm.agent.report.ApmServerHealthChecker - Elastic APM server http://localhost:8200/ is not available (Verbindungsaufbau abgelehnt)
2020-10-19 16:24:54,180 [elastic-apm-remote-config-poller] ERROR co.elastic.apm.agent.configuration.ApmServerConfigurationSource - Verbindungsaufbau abgelehnt
2020-10-19 16:24:54,181 [Attach Listener] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - Tracer switched to RUNNING state**_

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.4.RELEASE)

2020-10-19 16:24:54.383  INFO 48524 --- [           main] org.jstage.demo.DemoApplication          : Starting DemoApplication on N81 with PID 48524 (/home/thomashaarbach/Projekte/elastic-apm-test/target/classes started by thomashaarbach in /home/thomashaarbach/Projekte/elastic-apm-test)
2020-10-19 16:24:54.385  INFO 48524 --- [           main] org.jstage.demo.DemoApplication          : No active profile set, falling back to default profiles: default
2020-10-19 16:24:54.831  INFO 48524 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2020-10-19 16:24:54.837  INFO 48524 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-10-19 16:24:54.837  INFO 48524 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.38]
2020-10-19 16:24:54.876  INFO 48524 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-10-19 16:24:54.877  INFO 48524 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 430 ms
2020-10-19 16:24:54.982  INFO 48524 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-10-19 16:24:55.068  INFO 48524 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2020-10-19 16:24:55.077  INFO 48524 --- [           main] org.jstage.demo.DemoApplication          : Started DemoApplication in 0.843 seconds (JVM running for 1.975)
```

Test Execution:
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.4.RELEASE)

2020-10-19 16:25:56.623  INFO 48668 --- [           main] org.jstage.demo.DemoApplicationTests     : Starting DemoApplicationTests on N81 with PID 48668 (started by thomashaarbach in /home/thomashaarbach/Projekte/elastic-apm-test)
2020-10-19 16:25:56.625  INFO 48668 --- [           main] org.jstage.demo.DemoApplicationTests     : No active profile set, falling back to default profiles: default
2020-10-19 16:25:57.771  INFO 48668 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-10-19 16:25:58.006  INFO 48668 --- [           main] org.jstage.demo.DemoApplicationTests     : Started DemoApplicationTests in 1.746 seconds (JVM running for 2.951)

OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2020-10-19 16:25:58,784 [Attach Listener] INFO  co.elastic.apm.agent.util.JmxUtils - Found JVM-specific OperatingSystemMXBean interface: com.sun.management.OperatingSystemMXBean
2020-10-19 16:25:58,810 [Attach Listener] INFO  co.elastic.apm.agent.configuration.StartupInfo - Starting Elastic APM 1.18.1 as JUnitStarter on Java 14 Runtime version: 14+36-1461 VM version: 14+36-1461 (Oracle Corporation) Linux 5.8.15-201.fc32.x86_64
2020-10-19 16:25:58,810 [Attach Listener] WARN  co.elastic.apm.agent.configuration.StartupInfo - To enable all features and decrease startup time, please configure application_packages
2020-10-19 16:25:58,825 [Attach Listener] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - Tracer switched to RUNNING state
2020-10-19 16:25:58,827 [elastic-apm-server-healthcheck] WARN  co.elastic.apm.agent.report.ApmServerHealthChecker - Elastic APM server http://localhost:8200/ is not available (Verbindungsaufbau abgelehnt)
2020-10-19 16:25:58,827 [elastic-apm-remote-config-poller] ERROR co.elastic.apm.agent.configuration.ApmServerConfigurationSource - Verbindungsaufbau abgelehnt

```
</details>

### PR DESCRIPTION
**Pull request by SylvainJuge**
## What does this PR do?

Allow to completely disable the agent on startup, even when using remote and runtime attach.

Fixes #1444 

## Checklist

- [x] This is a bugfix
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [ ] I have added tests that would fail without this fix

Tested locally with runtime attach.

### CODE REVIEW

File: apm-agent-core/src/main/java/co/elastic/apm/agent/bci/ElasticApmAgent.java [hunk 1]
```diff
@@ -218,7 +230,7 @@ private static synchronized void initInstrumentation(final ElasticApmTracer trac
                 try {
                     File bytecodeDumpDir = Paths.get(bytecodeDumpPath).toFile();
                     if (!bytecodeDumpDir.exists()) {
-                        bytecodeDumpDir.mkdir();
+                        bytecodeDumpDir.mkdirs();
```
Comment (SylvainJuge) [inline apm-agent-core/src/main/java/co/elastic/apm/agent/bci/ElasticApmAgent.java:233]: this change is not related to the PR, it was just a quick bugfix

File: apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracerBuilder.java [hunk 2]
```diff
@@ -60,10 +60,10 @@
 import java.util.concurrent.TimeUnit;
 
 public class ElasticApmTracerBuilder {
-
     /**
      * See {@link co.elastic.apm.attach.ElasticApmAttacher#TEMP_PROPERTIES_FILE_KEY}
      */
+    @SuppressWarnings("JavadocReference")
```
Comment (SylvainJuge) [inline apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracerBuilder.java:66]: removes the javadoc error/warning from the comment just above due to field visibility

**Review by felixbarny — APPROVED** [review]
