### PR TITLE
Fix dynamic log_level configuration

### LINKED ISSUE #2366: Log level configuration is not fully dynamic
## Describe the bug
Logging level configuration is not fully dynamic after #2343 .
The [code](https://github.com/elastic/apm-agent-java/blob/master/apm-agent-core/src/main/java/co/elastic/apm/agent/logging/LoggingConfiguration.java#L342-L352) that sets the logging level is still applying the config for the agent CL context only, instead of applying to all agent CLs.
## Steps to reproduce
1. Start the agent with some logging level
2. Invoke some requests to load some instrumentation plugins
3. Change to a different level and wait until applied
4. Logging level of plugins does not change
## Expected behavior

Changing `log_level` in properties file should affect all agent loggers.

### PR DESCRIPTION
**Pull request by eyalkoren**
## What does this PR do?

Fixes #2366 
## Checklist

- [x] This is a bugfix
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [x] I have added tests that would fail without this fix
  - [x] I manually tested that plugin loggers' level changes when configuration changes

### CODE REVIEW

File: apm-agent-core/src/test/java/co/elastic/apm/agent/logging/LoggingConfigurationTest.java [hunk 1]
```diff
@@ -0,0 +1,206 @@
...
+            return null;
+        }
+    }
+
+    private static final class TestLog4jContextFactory extends Log4jContextFactory {
+
+        ContextSelector contextSelector = new TestContextSelector();
+
+        @Nullable
+        LoggerContext getContext(Logger slf4jLogger) {
```
Comment (jackshirazi) [inline apm-agent-core/src/test/java/co/elastic/apm/agent/logging/LoggingConfigurationTest.java:123]: why is this argument named `slf4jLogger` ?

Comment (eyalkoren) [reply apm-agent-core/src/test/java/co/elastic/apm/agent/logging/LoggingConfigurationTest.java:123]: Because it's an `org.slf4j.Logger`, as opposed to the `org.apache.logging.log4j.core.Logger` used two lines below. It's a utility for the test that only knows slf4j loggers.

**Review by jackshirazi — APPROVED** [review]
nice work
