### PR TITLE
enhance class name detection

### LINKED ISSUE #3686: Elastic APM Java agent cannot automatically infer the class name / object name for a span when using Scala and @CaptureSpan
## Describe the bug

According to the documentation [`@CaptureSpan` will automatically set the name of the span to `Classname#methodname`](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-capture-span). When using Scala 2, this works fine for classes but not for objects. For objects, only the `#methodname` is inferred but the `Classname` is just missing.

## Steps to reproduce

1. Use Scala 2.12.18 and `co.elastic.apm:apm-agent-api:1.50.0`.
2. Create a Scala class and object:
 ```scala
import co.elastic.apm.api.{CaptureSpan, ElasticApm, Transaction}

class Example {
  @CaptureSpan
  def myClassMethod() = println("Example#myClassMethod")
}

object Example {
  @CaptureSpan
  def myObjectMethod() = println("Example#myObjectMethod")
}

ElasticApm.startTransaction()

(new Example).myClassMethod()

Example.myObjectMethod()

ElasticApm.stopTransaction()
```
3. Run the code.
4. Check your Elastic APM instance for the captured spans.

## Expected behavior

Two spans are captured with the names:
1. `Example#myClassMethod`
2. `Example#myObjectMethod`

## Debug logs

n/a

### PR DESCRIPTION
**Pull request by wolframhaussig**
## What does this PR do?
Fixes #3686

## Checklist

- [ ] ~~This is an enhancement of existing features, or a new feature in existing plugins~~
  - [ ] ~~I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)~~
  - [ ] ~~I have added tests that prove my fix is effective or that my feature works~~
  - [ ] ~~Added an API method or config option? Document in which version this will be introduced~~
  - [ ] ~~I have made corresponding changes to the documentation~~
- [x] This is a bugfix
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [x] I have added tests that would fail without this fix
- [ ] ~~This is a new plugin~~
  - [ ] ~~I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)~~
  - [ ] ~~My code follows the [style guidelines of this project](https://github.com/elastic/apm-agent-java/blob/main/CONTRIBUTING.md#java-language-formatting-guidelines)~~
  - [ ] ~~I have made corresponding changes to the documentation~~
  - [ ] ~~I have added tests that prove my fix is effective or that my feature works~~
  - [ ] ~~New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/main/CONTRIBUTING.md#testing) pass locally with my changes~~
  - [ ] ~~I have updated [supported-technologies.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/docs/supported-technologies.asciidoc)~~
  - [ ] ~~Added an API method or config option? Document in which version this will be introduced~~
  - [ ] ~~Added an instrumentation plugin? Describe how you made sure that old, non-supported versions are not instrumented by accident.~~
- [ ] ~~This is something else~~
  - [ ] ~~I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)~~

### CODE REVIEW

File: apm-agent-plugin-sdk/src/main/java/co/elastic/apm/agent/sdk/bytebuddy/ClassNameParser.java [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+     * @return
+     */
+    public static String parse(String className) {
+        //remove package name
+        className = className.substring(className.lastIndexOf('.') + 1);
+        if(className.contains("$")) {
+            if(className.endsWith("$")) {
+                // this can happen if the source code was in Scala and the object keyword was used
+                // https://www.toptal.com/scala/scala-bytecode-and-the-jvm
+                className = className.substring(0, className.length() - 1);
```
Comment (JonasKunz) [inline apm-agent-plugin-sdk/src/main/java/co/elastic/apm/agent/sdk/bytebuddy/ClassNameParser.java:41]: What about nested objects, does this exist in Scala? E.g. `Outer$Inner$`

Comment (wolframhaussig) [reply apm-agent-plugin-sdk/src/main/java/co/elastic/apm/agent/sdk/bytebuddy/ClassNameParser.java:41]: I don't really know as I am not familiar with scala. Maybe the issue creator knows this @georgms

Comment (wolframhaussig) [reply apm-agent-plugin-sdk/src/main/java/co/elastic/apm/agent/sdk/bytebuddy/ClassNameParser.java:41]: Okay, I tried it out with https://scastie.scala-lang.org/ :

Nested classes is the same as in Java:  
```scala
class Graph:
  class Node:
    var connectedNodes: List[Node] = Nil
    def connectTo(node: Node): Unit =
      if !connectedNodes.exists(node.equals) then
        connectedNodes = node :: connectedNodes

  var nodes: List[Node] = Nil
  def newNode: Node =
    val res = Node()
    nodes = res :: nodes
    res

var g = Graph()
var n = g.newNode

Console.println(n.getClass().getName())
```

Output (removed Playground prefix which was added in  the web debugger):
> Graph$Node

For nested Objects, the same rules apply:  
```scala
import java.io.ObjectOutput
object Graph:
  object Node:
    def helloWorld(): Unit =
      Console.println("Hello World")


Console.println(Graph.Node.getClass().getName())
```

Output (removed Playground prefix which was added in  the web debugger):
> Graph$Node$

File: apm-agent-plugin-sdk/src/main/java/co/elastic/apm/agent/sdk/bytebuddy/ClassNameParser.java [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+            } else {
+                int dollarIndex = className.lastIndexOf('$');
+                String innerClassName = className.substring(dollarIndex + 1);
+                if(innerClassName.matches("\\d+")) {
```
Comment (JonasKunz) [inline apm-agent-plugin-sdk/src/main/java/co/elastic/apm/agent/sdk/bytebuddy/ClassNameParser.java]: Use a pre-compiled regex as constant here please (`Pattern`).
Alternatively you could also add a `isNumber(String)` utility method based on `Character.isDigit` to this class.

File: apm-agent-plugin-sdk/src/main/java/co/elastic/apm/agent/sdk/bytebuddy/ClassNameParser.java [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+                    // this is an anonymous inner class
+                    // we don't want to include the number in the class name
+                    className = className.substring(0, dollarIndex);
```
Comment (JonasKunz) [inline apm-agent-plugin-sdk/src/main/java/co/elastic/apm/agent/sdk/bytebuddy/ClassNameParser.java]: This can lead to cases where `Outer$1#method1()` leads to `Outer#method1()` while `Outer` doesn't have that method, which IMO is confusing.

I'd propose the following simple algorithm for dealing with nested class names:
* start with a string ([lastIndex($), endOfString])
* while the resulting string only contains `$` or numbers, start the string at the previous `$` instead (or index 0 if none exist anymore)

This will for example yield `Inner$1$2` for `Outer$Inner$1$2`, which in my opinion is the preferred result

**Review by JonasKunz — COMMENTED** [review]
LGTM, you'll just have to update the failing unit tests to match the new naming scheme

**Comment by wolframhaussig** [comment]
> LGTM, you'll just have to update the failing unit tests to match the new naming scheme

What do you mean, my tests are successfull?
image

**Comment by JonasKunz** [comment]
From the CI, the tests are in different projects:
```
2024-08-12T10:27:49.8805269Z [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.387 s <<< FAILURE! - in co.elastic.apm.agent.scheduled.TimerTaskInstrumentationTest
2024-08-12T10:27:49.8809648Z [ERROR] co.elastic.apm.agent.scheduled.TimerTaskInstrumentationTest.testTimerTask_withAnonymousClass  Time elapsed: 0.022 s  <<< FAILURE!
2024-08-12T10:27:49.8811696Z org.opentest4j.AssertionFailedError: 
2024-08-12T10:27:49.8812359Z 
2024-08-12T10:27:49.8812657Z expected: "1#run"
2024-08-12T10:27:49.8813191Z  but was: "TimerTaskInstrumentationTest$1#run"
2024-08-12T10:27:49.8814715Z 	at co.elastic.apm.agent.scheduled.TimerTaskInstrumentationTest.testTimerTask_withAnonymousClass(TimerTaskInstrumentationTest.java:83)
```

**Review by JonasKunz — APPROVED** [review]

**Comment by JonasKunz** [comment]
run docs-build

**Review by jackshirazi — APPROVED** [review]
