### PR TITLE
Fix log framework docs and log4j2 error instrumentation

### LINKED ISSUE #1116: Capture an APM error when an error message is logged through log4j2
We currently only capture errors when the `slf4j` and `log4j` APIs are used to log an error.
We want to fill this gap for `log4j2` as well.

### PR DESCRIPTION
**Pull request by felixbarny**
closes #1116

### CODE REVIEW

File: apm-agent-plugins/apm-error-logging-plugin/src/main/java/co/elastic/apm/agent/error/logging/Log4j2LoggerErrorCapturingInstrumentation.java [hunk 1]
```diff
@@ -29,18 +29,19 @@
...
 import static net.bytebuddy.matcher.ElementMatchers.named;
 import static net.bytebuddy.matcher.ElementMatchers.not;
 
-public class Log4jLoggingInstrumentation extends AbstractLoggingInstrumentation {
+public class Log4j2LoggerErrorCapturingInstrumentation extends AbstractLoggerErrorCapturingInstrumentation {
 
-    // prevents the shade plugin from relocating org.slf4j.Logger to co.elastic.apm.agent.shaded.slf4j.Logger
-    private static final String SLF4J_LOGGER = "org!slf4j!Logger".replace('!', '.');
+    // prevents the shade plugin from relocating org.apache.logging.log4j.Logger to co.elastic.apm.agent.shaded.logging.log4j.Logger
+    static final String LOG4J2_LOGGER = "org!apache!logging!log4j!Logger".replace('!', '.');
```
Comment (eyalkoren) [inline apm-agent-plugins/apm-error-logging-plugin/src/main/java/co/elastic/apm/agent/error/logging/Log4j2LoggerErrorCapturingInstrumentation.java:40]: 🤦  How come the test passed? We shade the tests as well?

Comment (felixbarny) [reply apm-agent-plugins/apm-error-logging-plugin/src/main/java/co/elastic/apm/agent/error/logging/Log4j2LoggerErrorCapturingInstrumentation.java:40]: We don’t shade the test, that’s why it succeeded in tests.

Comment (eyalkoren) [reply apm-agent-plugins/apm-error-logging-plugin/src/main/java/co/elastic/apm/agent/error/logging/Log4j2LoggerErrorCapturingInstrumentation.java:40]: Ohh, I guess you mean we test with non shaded agent code...
