### PR TITLE
Fixed Otel updateName behaviour

### LINKED ISSUE #2833: Allow updateName by opentelemtry Api.
We use the  plugin api to write a custom Hessian(http://hessian.caucho.com/doc/) plugin.  and want to update the span name, the span is created by the serlvet plugin, and updated by the spring mvc plugin. So
  `span.updateName()`, wich  call`withName(name, PRIO_DEFAULT)`, would not change the name.

Should  change the `span.updatename` to  call  `withName(name, PRIO_USER_SUPPLIED)`?
I found the apm api plugin `setName` call `withName(name, PRIO_USER_SUPPLIED)``

### PR DESCRIPTION
**Pull request by JonasKunz**
## What does this PR do?
Fixes #2833 

## Checklist

- [ ] This is an enhancement of existing features, or a new feature in existing plugins
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] I have made corresponding changes to the documentation
- [x] This is a bugfix
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [x] I have added tests that would fail without this fix
- [ ] This is a new plugin
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [ ] My code follows the [style guidelines of this project](https://github.com/elastic/apm-agent-java/blob/main/CONTRIBUTING.md#java-language-formatting-guidelines)
  - [ ] I have made corresponding changes to the documentation
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/main/CONTRIBUTING.md#testing) pass locally with my changes
  - [ ] I have updated [supported-technologies.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/docs/supported-technologies.asciidoc)
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] Added an instrumentation plugin? Describe how you made sure that old, non-supported versions are not instrumented by accident.
- [ ] This is something else
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)

### CODE REVIEW

File: apm-agent-plugins/apm-opentelemetry/apm-opentelemetry-plugin/src/main/java/co/elastic/apm/agent/opentelemetry/sdk/OTelSpan.java [hunk 1]
```diff
@@ -109,7 +109,7 @@ public Span recordException(Throwable exception, Attributes additionalAttributes
 
     @Override
     public Span updateName(String name) {
-        span.withName(name);
+        span.withName(name, AbstractSpan.PRIO_DEFAULT);
```
Comment (felixbarny) [inline apm-agent-plugins/apm-opentelemetry/apm-opentelemetry-plugin/src/main/java/co/elastic/apm/agent/opentelemetry/sdk/OTelSpan.java:112]:
```suggestion
        span.withName(name, AbstractSpan.PRIO_USER_SUPPLIED);
```

Comment (JonasKunz) [reply apm-agent-plugins/apm-opentelemetry/apm-opentelemetry-plugin/src/main/java/co/elastic/apm/agent/opentelemetry/sdk/OTelSpan.java]: oops, must have messed things up before commiting. At least it was caught by my own test :D

File: apm-agent-plugins/apm-opentelemetry/apm-opentelemetry-plugin/src/test/java/co/elastic/apm/agent/opentelemetry/sdk/ElasticOpenTelemetryTest.java [hunk 2]
```diff
@@ -449,6 +449,22 @@ public void otelSpanOverActiveElasticTransaction() {
...
+
+        try {
+            Span.current().updateName("Otel updated name");
+        } finally {
+            transaction.deactivate().end();
+        }
+
+        assertThat(reporter.getNumReportedTransactions()).isEqualTo(1);
+        assertThat(reporter.getFirstTransaction()).isSameAs(transaction);
+        assertThat(transaction.getNameAsString()).isEqualTo("Otel updated name");
```
Comment (SylvainJuge) [inline apm-agent-plugins/apm-opentelemetry/apm-opentelemetry-plugin/src/test/java/co/elastic/apm/agent/opentelemetry/sdk/ElasticOpenTelemetryTest.java:465]:
```suggestion
        assertThat(transaction).hasName("Otel updated name");
```

**Review by felixbarny — APPROVED** [review]
