### PR TITLE
implement fix for hp-ux version parsing

### LINKED ISSUE #1474: Support for Java 8 in HP-UX
I have a Hp-UX server withe Weblogic 12 that I am trying to instrument with the java agent elastic-apm-agent-1.18.1.jar. It seems that the numbering of the HP-UX releases of the java package is different from the official one so Java 1.8.0.17 corresponds to 1.8.0.202.
I receive the following errror when the instrumentation activates:
Failed to start agent - JVM version not supported: 1.8.0.17-hp-ux Java HotSpot(TM) 64-Bit Server VM 25.17-b1

Is it possible to disable this validation check? Is an HP-UV environment supported at all?

### PR DESCRIPTION
**Pull request by SylvainJuge**
## What does this PR do?

Fixes #1474 

Add an extra runtime property `elastic.apm.disable_bootstrap_checks` that allows to bypass JVM version check when it's value is set to `true`.

## Checklist

- [x] This is a bugfix
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [x] I have added tests that would fail without this fix
  - [x] I have updated [supported JVM version docs](https://www.elastic.co/guide/en/apm/agent/java/current/supported-technologies-details.html#supported-java-versions)
  - [x] I have documented the `elastic.apm.disable_bootstrap_checks` flag

### CODE REVIEW

**Review by felixbarny — APPROVED** [review]

File: apm-agent-core/src/main/java/co/elastic/apm/agent/bci/AgentMain.java [hunk 1]
```diff
@@ -82,9 +82,26 @@ public synchronized static void init(String agentArguments, Instrumentation inst
...
+            String msgTemplate;
+
+            boolean doDisable;
+            if (Boolean.parseBoolean(System.getProperty("elastic.apm.disable_bootstrap_checks"))) {
+                // safety check disabled, warn end user that it might
+                doDisable = false;
+                msgTemplate = "WARNING : JVM version unknown or not supported, safety check disabled - %s %s %s";
+            } else {
+                doDisable = true;
+                msgTemplate = "Failed to start agent - JVM version not supported: %s %s %s";
```
Comment (eyalkoren) [inline apm-agent-core/src/main/java/co/elastic/apm/agent/bci/AgentMain.java:95]:
```suggestion
                msgTemplate = "Failed to start agent - JVM version not supported: %s %s %s. To override Java version verification, set the "elastic.apm.disable_bootstrap_checks" System property to "true".";
```

**Review by eyalkoren — COMMENTED** [review]
Nice.
We need to document the `disable_bootstrap_checks` flag somehow.
See suggestion to do that when aborting at startup. 

In addition, I think we can at least add it to the `NOTE` message we have at the [supported Java version section](https://www.elastic.co/guide/en/apm/agent/java/current/supported-technologies-details.html#supported-java-versions).
This section needs to be updated to include these new JVM limitations as well.

**Review by eyalkoren — APPROVED** [review]
