### PR TITLE
Instrument View#render instead of DispatcherServlet#render

### LINKED ISSUE #811: Revise rendering spans
Today we're instrumenting `DispatcherServlet#render` and create a span for it. This works well in order to have a span in the waterfall. What doesn't work well is how it appears in the breakdown graph. That's because the `type=template`, `subtype=dispatcher-servlet`, `action=render`. There's no indication of what technology is used to render the template. it would also attribute JSON serialization as `template` where `serialization` may suit better.

Proposal:
Don't instrument `DispatcherServlet#render`. Instead, instrument the `render` method of `org.springframework.web.servlet.View` implementations. Some example are `JasperReportsXlsxView`, `FreeMarkerView` and `MappingJackson2JsonView`.

```java
String type = "template";
String subtype = view.getClass().getSimpleName().replace("View", "");
String action = "render";
```

Not sure if needed or not but for things like JSON serialization we might want a different type than `template`.
```java
if (view.getClass().getName().containsAnyIgnoreCase("json", "xml", ...)) {
    type = "serialization";
    subtype = "json"/"xml"?
}
```

/cc @roncohen

### PR DESCRIPTION
**Pull request by kananindzya**
### Checklist

closes elastic/apm-agent-java#811 
- [x] Implement code
- [x] Add tests
-- [x] jsp
-- [x] markup templates
-- [x] freemarker
-- [x] groovy templates
-- [x] jackson2json view
-- [x] jade4j template
- [ ] Update documentation
- [x] Update [CHANGELOG.md](CHANGELOG.md)
- [x] Update [supported-technologies.asciidoc](docs/supported-technologies.asciidoc)
- [ ] Added an API method or config option? Document in which version this will be introduced.

### CODE REVIEW

**Comment by kananindzya** [comment]
Hi @felixbarny ,
please review pull request.

**Comment by kananindzya** [comment]
image
image

File: apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java [hunk 1]
```diff
@@ -0,0 +1,123 @@
...
+
+        @Advice.OnMethodEnter(suppress = Throwable.class)
+        public static void beforeExecute(@Advice.Local("span") @Nullable Span span,
+                                         @Advice.This @Nullable Object thiz) {
+            if (tracer == null || tracer.getActive() == null) {
+                return;
+            }
+            final TraceContextHolder<?> parent = tracer.getActive();
+
+            String viewClassName = thiz.getClass().getSimpleName().replace("View", "");
```
Comment (felixbarny) [inline apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java]: We can be a bit more efficient here. 

Similar to this (I have not tested it)

```java
StringBuilder name = span.getAndOverrideName(PRIO_DEFAULT);
if (name != null) {
    String className = thiz.getClass().getName();
    name.append(className, className.lastIndexOf('.'), className.lastIndexOf("View"));
}
```

File: apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+                .withName(DISPATCHER_SERVLET_RENDER_METHOD);
+
+            String viewName = null;
+            if (thiz instanceof AbstractView) {
+                AbstractView view = (AbstractView) thiz;
+                viewName = view.getBeanName();
+            }
+            switch (viewClassName) {
+                case "Thymeleaf":
+                    AbstractThymeleafView view = (AbstractThymeleafView) thiz;
```
Comment (felixbarny) [inline apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java]: This may cause linkage errors if `AbstractThymeleafView` is not on the class path. Better to invoke it via reflection. It's also ok to just not support `AbstractThymeleafView` in the first version. We can always add that later.

File: apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+    public ElementMatcher<? super MethodDescription> getMethodMatcher() {
+        return named("render")
+            .and(takesArgument(0, named("java.util.Map")))
+            .and(takesArgument(1, named("javax.servlet.http.HttpServletRequest")))
+            .and(takesArgument(2, named("javax.servlet.http.HttpServletResponse")));
+    }
+
+    @Override
+    public Collection<String> getInstrumentationGroupNames() {
+        return Arrays.asList("thymeleaf-view", "freemarker-view", "jackson2json-view", "jsp-view", "groovy-template-view", "jade4j-template-view");
```
Comment (felixbarny) [inline apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java]:
```suggestion
        return Arrays.asList("spring-view-render");
```

File: apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java [hunk 4]
```diff
@@ -0,0 +1,123 @@
...
+        public static void afterExecute(@Advice.Local("span") @Nullable Span span,
+                                        @Advice.Thrown @Nullable Throwable t) {
+            if (span != null) {
+                span.captureException(t)
+                    .deactivate()
+                    .end();
+            }
+        }
+    }
+
```
Comment (felixbarny) [inline apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java]: add a `getTypeMatcherPreFilter` with `nameContains("View")` to speed up the matching 🙂

File: apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java (hunk 2 above)
Comment (kananindzya) [reply apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java]: removed

File: apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java (hunk 4 above)
Comment (kananindzya) [reply apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java]: added

File: apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java (hunk 3 above)
Comment (kananindzya) [reply apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java]: changed

File: apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java (hunk 1 above)
Comment (kananindzya) [reply apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java]: replaced on:
```
 String className = thiz.getClass().getName();
            span = parent.createSpan()
                .withType(SPAN_TYPE)
                .withSubtype(className.substring(className.lastIndexOf('.')+1, className.lastIndexOf("View")))
                .withAction(SPAN_ACTION)
                .withName(DISPATCHER_SERVLET_RENDER_METHOD);

```

Comment (felixbarny) [reply apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java]: Substring still creates a new object. With my suggestion, there would be no allocation involved as it just copies over a range of characters from the class name string to the string builder.

Comment (felixbarny) [reply apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java]: oh, right 🤦‍♂️
nevermind then

File: apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java [hunk 5]
```diff
@@ -0,0 +1,117 @@
...
+                                         @Advice.This @Nullable Object thiz) {
+            if (tracer == null || tracer.getActive() == null) {
+                return;
+            }
+            final TraceContextHolder<?> parent = tracer.getActive();
+
+            String className = thiz.getClass().getName();
+            span = parent.createSpan()
+                .withType(SPAN_TYPE)
+                .withSubtype(className.substring(className.lastIndexOf('.')+1, className.lastIndexOf("View")))
```
[the remark this answers is not in the document]
Comment (kananindzya) [reply apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java]: @eyalkoren 
Should I add this method: 
```
        public static String defineSubtype(String className) {
            switch (className) {
                case "org.springframework.web.servlet.view.groovy.GroovyMarkupView":
                    return "GroovyMarkup";
                case "org.springframework.web.servlet.view.freemarker.FreeMarkerView":
                    return "FreeMarker";
                case "org.springframework.web.servlet.view.json.MappingJackson2JsonView":
                    return "MappingJackson2Json";
                case "de.neuland.jade4j.spring.view.JadeView":
                    return "Jade";
                case "org.springframework.web.servlet.view.InternalResourceView":
                    return "InternalResource";
                case "org.thymeleaf.spring4.view.ThymeleafView":
                    return "Thymeleaf";
                default:
                    break;
            }
            return className.substring(className.lastIndexOf('.')+1, className.lastIndexOf("View"));
        }
```
?

[the remark this answers is not in the document]
Comment (kananindzya) [reply apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java]: added

File: apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java [hunk 6]
```diff
@@ -0,0 +1,143 @@
...
+        public static void afterExecute(@Advice.Local("span") @Nullable Span span,
+                                        @Advice.Thrown @Nullable Throwable t) {
+            if (span != null) {
+                span.captureException(t)
+                    .deactivate()
+                    .end();
+            }
+        }
+
+        public static String defineSubtype(String className) {
```
Comment (eyalkoren) [inline apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java]:
```suggestion
        @VisibleForAdvice
        public static String obtainSubtype(String className) {
```

File: apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java [hunk 7]
```diff
@@ -106,9 +106,14 @@ public static String defineSubtype(String className) {
                 case "org.thymeleaf.spring4.view.ThymeleafView":
                     return "Thymeleaf";
                 default:
-                    break;
+                    if (subTypeCache.containsKey(className)) {
```
Comment (eyalkoren) [inline apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java]: Usually it's better get and check if `null`, as in:
```
String subType = subTypeCache.get(className);
if (subType == null) {
    subType = className.substring(className.lastIndexOf('.') + 1, className.lastIndexOf("View"));
    if (subTypeCache.size() < 1000) {
        subTypeCache.put(className, subType);
    }
}
return sunType;
```
Then it's one lookup in the cache instead of two every time

File: apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java [hunk 8]
```diff
@@ -0,0 +1,143 @@
...
+                case "org.springframework.web.servlet.view.InternalResourceView":
+                    return "InternalResource";
+                case "org.thymeleaf.spring4.view.ThymeleafView":
+                    return "Thymeleaf";
+                default:
+                    if (subTypeCache.containsKey(className)) {
+                        return subTypeCache.get(className);
+                    } else {
+                        String subType = className.substring(className.lastIndexOf('.') + 1, className.lastIndexOf("View"));
+                        subTypeCache.put(className, subType);
```
Comment (eyalkoren) [inline apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java]:
```suggestion
                        if (subTypeCache.size() < 1000) {
                            subTypeCache.put(className, subType);
                        }
```
Just precaution from strange unknown scenarios

**Comment by felixbarny** [comment]
I've added the suggestions, hope you don't mind 🙂 
Also found and fixed some edge cases which could lead to a `StringIndexOutOfBoundsException` for really strange class names and for those not containing `"View"`.

**Comment by kananindzya** [comment]
> I've added the suggestions, hope you don't mind slightly_smiling_face
> Also found and fixed some edge cases which could lead to a `StringIndexOutOfBoundsException` for really strange class names and for those not containing `"View"`.

Thanks :) 
I also thought about classes without packages

**Comment by felixbarny** [comment]
Thanks for bearing with us even if it sometimes takes some time to get changes in, but we really appreciate it!
