### PR TITLE
Universal profiling integration: Add stacktrace-IDs to transactions

### LINKED ISSUE #3407: Implement JNI communication mechanism with the universal profiling host agent
* Add the infrastructure for writing and compile JNI C++ code (resulting binaries will be checked-in in git for now)
* Implement and test the communication mechanism with the host-agent:
  * Shared process-storage
  * Shared thead-local-storage
  * Message receival
  
The goal of this issue is to implement and test these features, but to not have them active in the agent yet.

### PR DESCRIPTION
**Pull request by JonasKunz**
## What does this PR do?

Closes #3407, #3408, #3409.

With this PR, the universal profiling integration will become functional. I did some manual testing with the `Host Agent 8.14.0 (revision head-579692d4, build timestamp 1714465797)`.

This PR is mostly a port of the implementation from [elastic-otel-java](https://github.com/elastic/elastic-otel-java).

## Checklist

- [x] This is an enhancement of existing features, or a new feature in existing plugins
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [x] I have added tests that prove my fix is effective or that my feature works
  - [x] Added an API method or config option? Document in which version this will be introduced
  - [x] I have made corresponding changes to the documentation

### CODE REVIEW

File: apm-agent-core/src/main/java/co/elastic/apm/agent/universalprofiling/PeekingPoller.java [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+import com.lmax.disruptor.EventPoller;
+
+import java.util.function.Supplier;
+
+/**
+ * Wrapper around {@link EventPoller} which allows to "peek" elements. The provided event handling
+ * callback can decide to not handle an event. In that case, the event will be provided again as
+ * first element on the next call to {@link #poll(Handler)}.
+ */
+public class PeekingPoller<Event extends MoveableEvent<Event>> {
```
Comment (JonasKunz) [inline apm-agent-core/src/main/java/co/elastic/apm/agent/universalprofiling/PeekingPoller.java:31]: This class and the tests are a copy of https://github.com/elastic/elastic-otel-java/blob/main/universal-profiling-integration/src/main/java/co/elastic/otel/disruptor/PeekingPoller.java.

The only changes made are removal of Java-8 feature usages.

File: apm-agent-core/src/main/java/co/elastic/apm/agent/universalprofiling/SpanProfilingSamplesCorrelator.java [hunk 2]
```diff
@@ -0,0 +1,218 @@
...
+import com.lmax.disruptor.EventFactory;
+import com.lmax.disruptor.EventPoller;
+import com.lmax.disruptor.EventTranslatorTwoArg;
+import com.lmax.disruptor.RingBuffer;
+import com.lmax.disruptor.YieldingWaitStrategy;
+import org.HdrHistogram.WriterReaderPhaser;
+
+import java.util.concurrent.ConcurrentHashMap;
+
+public class SpanProfilingSamplesCorrelator {
```
Comment (JonasKunz) [inline apm-agent-core/src/main/java/co/elastic/apm/agent/universalprofiling/SpanProfilingSamplesCorrelator.java:36]: This class is a port of https://github.com/elastic/elastic-otel-java/blob/main/universal-profiling-integration/src/main/java/co/elastic/otel/SpanProfilingSamplesCorrelator.java.

The logic and methods are broadly the same, just ported from Otel to our `elastic-apm-agent` datastructures.

**Review by jackshirazi — APPROVED** [review]
