### PR TITLE
Fix security manager issues

### LINKED ISSUE #2520: NoClassDefFound with Tomcat + Security Manager
When a security manager is configured in Tomcat (might also happen with other server/apps), the standard output is polluted with lots of `NoClassDefFoundError` errors.

How to reproduce:
- grant agent every permission in `conf/catalina.policy` , for example: 
  ```
  grant codeBase "file:/path/to-agent/elastic-apm-agent-1.29.1-SNAPSHOT.jar" {
    permission java.security.AllPermission;
  };
  ```
- start tomcat with `bin/catalina.sh run -security`

Agent version: 1.29.0 + same on main as of writing
Tomcat version: 9.0.x

Setting `warmup_byte_buddy=false` does not makes a difference here.
While the symptoms might be similar, the fix for #2509 does not cover this case, thus it might not be related but similar.

<details>
  <summary>catalina.out output</summary>
 
  ```
  2022-03-17 10:31:22,251 [main] INFO  co.elastic.apm.agent.util.JmxUtils - Found JVM-specific OperatingSystemMXBean interface: com.sun.management.OperatingSystemMXBean
2022-03-17 10:31:22,290 [main] INFO  co.elastic.apm.agent.configuration.StartupInfo - Starting Elastic APM 1.29.1-SNAPSHOT.UNKNOWN as tomcat-application on Java 11.0.8 Runtime version: 11.0.8+10 VM version: 11.0.8+10 (AdoptOpenJDK) Linux 5.13.0-30-generic
2022-03-17 10:31:22,290 [main] INFO  co.elastic.apm.agent.configuration.StartupInfo - warmup_byte_buddy: 'false' (source: Java System Properties)
2022-03-17 10:31:22,290 [main] WARN  co.elastic.apm.agent.configuration.StartupInfo - To enable all features and decrease startup time, please configure application_packages
2022-03-17 10:31:23,417 [main] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - Tracer switched to RUNNING state
2022-03-17 10:31:23,450 [elastic-apm-server-healthcheck] INFO  co.elastic.apm.agent.report.ApmServerHealthChecker - Elastic APM server is available: {  "build_date": "2022-02-03T16:50:25Z",  "build_sha": "6afb387ae002e5a8dc2427b53225aa42681e4208",  "publish_ready": true,  "version": "8.0.0"}
17-Mar-2022 10:31:23.766 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.38
17-Mar-2022 10:31:23.769 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Sep 10 2020 08:20:30 UTC
17-Mar-2022 10:31:23.769 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.38.0
17-Mar-2022 10:31:23.769 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
17-Mar-2022 10:31:23.769 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.13.0-30-generic
17-Mar-2022 10:31:23.769 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
17-Mar-2022 10:31:23.769 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /home/sylvain/.sdkman/candidates/java/11.0.8.hs-adpt
17-Mar-2022 10:31:23.769 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.8+10
17-Mar-2022 10:31:23.770 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            AdoptOpenJDK
17-Mar-2022 10:31:23.770 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /home/sylvain/tools/tomcat/apache-tomcat-9.0.38
17-Mar-2022 10:31:23.770 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /home/sylvain/tools/tomcat/apache-tomcat-9.0.38
17-Mar-2022 10:31:23.770 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
17-Mar-2022 10:31:23.770 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
17-Mar-2022 10:31:23.770 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
17-Mar-2022 10:31:23.770 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/home/sylvain/tools/tomcat/apache-tomcat-9.0.38/conf/logging.properties
17-Mar-2022 10:31:23.771 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
17-Mar-2022 10:31:23.771 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
17-Mar-2022 10:31:23.771 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
17-Mar-2022 10:31:23.771 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
17-Mar-2022 10:31:23.771 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -javaagent:/home/sylvain/dev/apm-agent-java_security-manager-warn/elastic-apm-agent/target/elastic-apm-agent-1.29.1-SNAPSHOT.jar
17-Mar-2022 10:31:23.771 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Delastic.apm.warmup_byte_buddy=false
17-Mar-2022 10:31:23.771 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
17-Mar-2022 10:31:23.771 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.security.manager
17-Mar-2022 10:31:23.771 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.security.policy==/home/sylvain/tools/tomcat/apache-tomcat-9.0.38/conf/catalina.policy
17-Mar-2022 10:31:23.771 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/home/sylvain/tools/tomcat/apache-tomcat-9.0.38
17-Mar-2022 10:31:23.772 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/home/sylvain/tools/tomcat/apache-tomcat-9.0.38
17-Mar-2022 10:31:23.772 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/home/sylvain/tools/tomcat/apache-tomcat-9.0.38/temp
17-Mar-2022 10:31:23.773 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The Apache Tomcat Native library which allows using OpenSSL was not found on the java.library.path: [/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib]
17-Mar-2022 10:31:24.011 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
17-Mar-2022 10:31:24.057 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [471] milliseconds
17-Mar-2022 10:31:24.115 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
17-Mar-2022 10:31:24.116 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.38]
17-Mar-2022 10:31:24.124 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/home/sylvain/tools/tomcat/apache-tomcat-9.0.38/webapps/docs]
java.lang.NoClassDefFoundError: co/elastic/apm/agent/servlet/ServletServiceNameHelper
	at co.elastic.apm.agent.servlet.servicename.ServletContainerInitializerServiceNameInstrumentation$JavaxInitServiceNameInstrumentation$AdviceClass.onEnter(ServletContainerInitializerServiceNameInstrumentation.java:89)
	at org.apache.jasper.servlet.JasperInitializer.onStartup(JasperInitializer.java:60)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5128)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
	at org.apache.catalina.core.ContainerBase.access$000(ContainerBase.java:129)
	at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:150)
	at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:140)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:688)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:706)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1133)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1866)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
	at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1045)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:429)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
Caused by: java.lang.ClassNotFoundException: co.elastic.apm.agent.servlet.ServletServiceNameHelper
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader.findClass(ByteArrayClassLoader.java:403)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader$ChildFirst.loadClass(ByteArrayClassLoader.java:1265)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 46 more

  ```
</details>

### PR DESCRIPTION
**Pull request by SylvainJuge**
## What does this PR do?

Fixes #2520 

- fixes `NoClassDefFound` errors triggered in classloading due to URL validation in JDK outside of a `doPrivileged` wrapping.
- fixes few missing `doPrivileged` calls to make the agent able to start properly (reading environment variables, get classloader reference of an existing class and resolve method handles).
- surprisingly, some of the calls to `System.getenv` trigger exception when not called in a privileged action, whereas the `System.getProperty` or `System.getProperties` do not, as a result I added a `PrivilegedActionUtils` class to properly wrap those calls with minimal code duplication and verbosity.

## Checklist

- [x] This is a bugfix
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [x] I have added tests that would fail without this fix. tests will be provided by https://github.com/elastic/apm-agent-java/pull/2883.
  - [x] Manual tests with Tomcat 9.0.38 + JDK 11.0.8 + security manager enabled, started with `./bin/catalina.sh run -security` + enabling most agent features (log reformatting, inferred spans, ...)

### CODE REVIEW

File: elastic-apm-agent/src/main/java/co/elastic/apm/agent/premain/ShadedClassLoader.java [hunk 1]
```diff
@@ -204,11 +228,26 @@ private byte[] getShadedClassBytes(String name) throws ClassNotFoundException {
...
+
+            // while most of the body of default 'findResource' in JDK implementation is in a privileged action
+            // an extra URL check is performed just after it, hence we have to wrap the whole method call in a privileged
+            // action otherwise the security manager will complain about lack of proper read privileges on the agent jar
+            result = AccessController.doPrivileged(new PrivilegedAction<URL>() {
+                @Override
+                public URL run() {
+                    return findResourceInternal(getShadedResourceName(name));
+                }
+            });
```
Comment (SylvainJuge) [inline elastic-apm-agent/src/main/java/co/elastic/apm/agent/premain/ShadedClassLoader.java:243]: [for reviewer] this fixes the `NoClassDefFound` exceptions, the JDK implementation of `findResource` that we call through the `super.findResource(name)` performs an extra URL check outside of a privileged action.

File: apm-agent-core/src/main/java/co/elastic/apm/agent/bci/IndyBootstrap.java [hunk 2]
```diff
@@ -354,10 +356,21 @@ static void setJavaBaseModule(Class<?> targetClass) throws Throwable {
...
-                                             String adviceMethodName,
-                                             MethodType adviceMethodType,
-                                             Object... args) {
+    public static ConstantCallSite bootstrap(final MethodHandles.Lookup lookup,
+                                             final String adviceMethodName,
+                                             final MethodType adviceMethodType,
+                                             final Object... args) {
+
+        // callsite resolution needs privileged access to call Class#getClassLoader() and MethodHandles$Lookup#findStatic
+        return AccessController.doPrivileged(new PrivilegedAction<ConstantCallSite>() {
```
Comment (eyalkoren) [inline apm-agent-core/src/main/java/co/elastic/apm/agent/bci/IndyBootstrap.java:365]: Can we reuse the same `PrivilegedAction` instance here? This is called very intensively at startup, so if we can avoid this overhead, that would be nice.
I think it will make the code even nicer, where the actual implementation is located within the privileged action implementation.

File: elastic-apm-agent/src/main/java/co/elastic/apm/agent/premain/ShadedClassLoader.java [hunk 3]
```diff
@@ -157,7 +160,15 @@ private Class<?> defineClass(String name, byte[] classBytes) {
                 }
             }
         }
-        return defineClass(name, classBytes, 0, classBytes.length, ShadedClassLoader.class.getProtectionDomain());
+
+        ProtectionDomain protectionDomain = AccessController.doPrivileged(new PrivilegedAction<ProtectionDomain>() {
```
Comment (eyalkoren) [inline elastic-apm-agent/src/main/java/co/elastic/apm/agent/premain/ShadedClassLoader.java:164]: This allocates a `PrivilegedAction` instance for every loaded class, although we only need a single `ProtectionDomain`. Let's execute this once and keep the reference for this `ProtectionDomain`.

File: elastic-apm-agent/src/main/java/co/elastic/apm/agent/premain/ShadedClassLoader.java [hunk 4]
```diff
@@ -196,6 +207,19 @@ private byte[] getShadedClassBytes(String name) throws ClassNotFoundException {
         return null;
     }
 
+    private InputStream getPrivilegedResourceAsStream(final String name) {
+        return AccessController.doPrivileged(new PrivilegedAction<InputStream>() {
```
Comment (eyalkoren) [inline elastic-apm-agent/src/main/java/co/elastic/apm/agent/premain/ShadedClassLoader.java:211]: Same - preferably avoid allocation if possible.

File: elastic-apm-agent/src/main/java/co/elastic/apm/agent/premain/ShadedClassLoader.java [hunk 5]
```diff
@@ -204,11 +228,26 @@ private byte[] getShadedClassBytes(String name) throws ClassNotFoundException {
...
-        if (locallyNonAvailableResources.get().contains(name)) {
-            return null;
+    public URL findResource(final String name) {
+        URL result = null;
+        if (!locallyNonAvailableResources.get().contains(name)) {
+
+            // while most of the body of default 'findResource' in JDK implementation is in a privileged action
+            // an extra URL check is performed just after it, hence we have to wrap the whole method call in a privileged
+            // action otherwise the security manager will complain about lack of proper read privileges on the agent jar
+            result = AccessController.doPrivileged(new PrivilegedAction<URL>() {
```
Comment (eyalkoren) [inline elastic-apm-agent/src/main/java/co/elastic/apm/agent/premain/ShadedClassLoader.java:238]: same

File: elastic-apm-agent/src/main/java/co/elastic/apm/agent/premain/ShadedClassLoader.java [hunk 6]
```diff
@@ -219,11 +258,12 @@ public URL findResource(String name) {
...
-    public Enumeration<URL> findResources(String name) throws IOException {
-        if (locallyNonAvailableResources.get().contains(name)) {
-            return null;
+    public Enumeration<URL> findResources(final String name) throws IOException {
+        Enumeration<URL> result = null;
+        if (!locallyNonAvailableResources.get().contains(name)) {
+            result = super.findResources(getShadedResourceName(name));
         }
-        return super.findResources(getShadedResourceName(name));
+        return new PrivilegedEnumeration<URL>(result);
```
Comment (eyalkoren) [inline elastic-apm-agent/src/main/java/co/elastic/apm/agent/premain/ShadedClassLoader.java:266]: I think a better alternative is to use the `URLClassLoader` constructor that accepts `AccessControlContext` when constructing this `ShadedClassLoader` with `AccessController.getContext()`. If I understand correctly, it will be automatically used in the `findResource` enumeration.

**Review by eyalkoren — COMMENTED** [review]
Awesome fix!! 👏 
See comments

**Comment by SylvainJuge** [comment]
@eyalkoren avoiding allocation here might be something quite challenging, especially for the cases when there are multiple parameters, do you think that would be required ?

Alternatively, maybe a simpler approach here would be to simply shortcut this extra wrapping when `System.getSecurityManager() == null` and avoid this extra allocation when security manager is disabled. My assumption here is that users of Security Manager do not have strong expectations in memory allocation as their application is very likely to have to perform similar wrapping with privileged actions. I will update this PR to this approach and we can further discuss the final implementation.

**Comment by SylvainJuge** [comment]
Status:
- I have used a rather simple but tedious approach to delegate to a utility class in order to wrap with `AccessController.doPrivileged`
- doing this means we have to review and modify where the agent might call the security manager through multiple code paths.
- this PR does not yet cover all aspects, for example all the file access by the agent or the logger plugins will trigger the security manager issues.
- there might be a better and more generic approach that we need to discuss further.

File: elastic-apm-agent/src/main/java/co/elastic/apm/agent/premain/ShadedClassLoader.java (hunk 6 above)
Comment (eyalkoren) [reply elastic-apm-agent/src/main/java/co/elastic/apm/agent/premain/ShadedClassLoader.java:280]: Hmm, that is super odd! 
I wonder if this was just overlooked, or intentional. It seems to completely miss the purpose of the custom `AccessControlContext` and looks very easy to get right. In fact it seems to obvious, that I assume we are missing something here.
Well, if this doesn't help, I guess you need to do what you need to do...

Comment (eyalkoren) [reply elastic-apm-agent/src/main/java/co/elastic/apm/agent/premain/ShadedClassLoader.java:280]: The thing is that the internal `URLClassPath` (the `URLClassLoader#ucp` field) is constructed with the provided `AccessControlContext`, so it could have been easily done if `checkURL()` was not a static method.

**Comment by eyalkoren** [comment]
> Alternatively, maybe a simpler approach here would be to simply shortcut this extra wrapping when System.getSecurityManager() == null and avoid this extra allocation when security manager is disabled. 

Definitely, this sounds very reasonable. Just let's not have this overhead penalty to the vast majority of users that don't use the security manager.

File: apm-agent-core/src/main/java/co/elastic/apm/agent/bci/IndyBootstrap.java (hunk 2 above)
Comment (SylvainJuge) [reply apm-agent-core/src/main/java/co/elastic/apm/agent/bci/IndyBootstrap.java:370]: we now avoid this extra allocation when SM is disabled (default)

File: apm-agent-core/src/main/java/co/elastic/apm/agent/logging/Log4j2LoggerBridge.java [hunk 7]
```diff
@@ -44,151 +47,235 @@ public String getName() {
...
-        log4jLogger.logIfEnabled(FQCN, Level.ERROR, null, format, args);
+        logIfEnabled(Level.ERROR, format, args);
     }
 
     @Override
     public void error(final String format, final Throwable t) {
-        log4jLogger.logIfEnabled(FQCN, Level.ERROR, null, format, t);
+        logIfEnabled(Level.ERROR, format, t);
+    }
+
```
Comment (SylvainJuge) [inline apm-agent-core/src/main/java/co/elastic/apm/agent/logging/Log4j2LoggerBridge.java:197]: [for reviewer] calls the the logger might open files for writing when 1) creating the log file, or 2) rotating the log file, thus we have to wrap all logger calls with elevated privileges.

File: apm-agent-core/src/main/java/co/elastic/apm/agent/bci/classloading/IndyPluginClassLoader.java [hunk 8]
```diff
@@ -41,9 +43,15 @@ public class IndyPluginClassLoader extends ByteArrayClassLoader.ChildFirst {
 
     public IndyPluginClassLoader(@Nullable ClassLoader targetClassLoader, ClassLoader agentClassLoader, Map<String, byte[]> typeDefinitions) {
         // See getResource on why we're using PersistenceHandler.LATENT over PersistenceHandler.MANIFEST
-        super(getParent(targetClassLoader, agentClassLoader), true, typeDefinitions, PersistenceHandler.LATENT);
+        super(getParent(targetClassLoader, agentClassLoader),
+            true,
+            typeDefinitions,
+            PrivilegedActionUtils.getProtectionDomain(agentClassLoader.getClass()), // inherit protection domain from agent CL
```
Comment (SylvainJuge) [inline apm-agent-core/src/main/java/co/elastic/apm/agent/bci/classloading/IndyPluginClassLoader.java:49]: [for reviewer] this change allows to provide the protection domain that will be used for classes that are loaded through tne `IndyPluginClassLoader`, without that, we get a `null` protection domain for classes that are loaded by this CL, hence making us unable to get the right permissions in advice code, even with `doPrivileged` wrapping.

**Comment by eyalkoren** [comment]
Closes #390

File: apm-agent-plugin-sdk/src/main/java/co/elastic/apm/agent/sdk/internal/InternalUtil.java [hunk 9]
```diff
@@ -0,0 +1,53 @@
...
+
+        return AccessController.doPrivileged(new PrivilegedAction<ClassLoader>() {
+            @Override
+            public ClassLoader run() {
+                return doGetClassLoader(type, systemFallback);
+            }
+        });
+    }
+
+    private static ClassLoader doGetClassLoader(Class<?> type, boolean systemFallback) {
```
Comment (eyalkoren) [inline apm-agent-plugin-sdk/src/main/java/co/elastic/apm/agent/sdk/internal/InternalUtil.java:46]: `systemFallback` is not used.
I think this bug (the logic of one call to this method actually had changed) is due to the misleading API. 
It would be much safer if this utility class would do only what it needs to do, which is to wrap `getClassLoader` and `getSystemClassLoader` with `PrivilegedAction` if required and the caller would decide what to do with `null`.

File: apm-agent-plugins/apm-logging-plugin/apm-jul-plugin/src/main/java/co/elastic/apm/agent/jul/reformatting/AbstractJulEcsReformattingHelper.java [hunk 10]
```diff
@@ -112,6 +115,26 @@ protected Handler createAndStartEcsAppender(Handler originalHandler, String ecsA
...
+        }
+        try {
+            return AccessController.doPrivileged(new PrivilegedExceptionAction<FileHandler>() {
+                @Override
+                public FileHandler run() throws Exception {
+                    return doCreateFileHandler(pattern, maxLogFileSize);
+                }
+            });
+        } catch (PrivilegedActionException e) {
+            throw (IOException) e.getCause();
```
Comment (eyalkoren) [inline apm-agent-plugins/apm-logging-plugin/apm-jul-plugin/src/main/java/co/elastic/apm/agent/jul/reformatting/AbstractJulEcsReformattingHelper.java:130]: should we extract cause and cast?

File: apm-agent-plugin-sdk/src/main/java/co/elastic/apm/agent/sdk/state/GlobalVariables.java [hunk 11]
```diff
@@ -51,7 +53,7 @@ public class GlobalVariables {
      */
     public static <T> T get(Class<?> adviceClass, String key, T defaultValue) {
         key = adviceClass.getName() + "." + key;
-        if (defaultValue.getClass().getClassLoader() != null && !defaultValue.getClass().getName().startsWith("co.elastic.apm.agent")) {
+        if (InternalUtil.getClassLoader(defaultValue.getClass(), false) == null && !defaultValue.getClass().getName().startsWith("co.elastic.apm.agent")) {
```
Comment (eyalkoren) [inline apm-agent-plugin-sdk/src/main/java/co/elastic/apm/agent/sdk/state/GlobalVariables.java:56]: `InternalUtil.getClassLoader(defaultValue.getClass(), false)` currently can't return `null`

**Review by eyalkoren — COMMENTED** [review]
What a magnificent refactoring! 👏 
Looks really good and I recognized lots of stuff I saw failing in #2883, which is a good indication that we are in the right direction.

Some minor comments still.

File: apm-agent-plugin-sdk/src/main/java/co/elastic/apm/agent/sdk/state/GlobalVariables.java (hunk 11 above)
Comment (SylvainJuge) [reply apm-agent-plugin-sdk/src/main/java/co/elastic/apm/agent/sdk/state/GlobalVariables.java:56]: good catch, and also I did introduce a bug here, thus adding a test is required.

File: apm-agent-core/src/main/java/co/elastic/apm/agent/bci/classloading/IndyPluginClassLoader.java (hunk 8 above)
Comment (eyalkoren) [reply apm-agent-core/src/main/java/co/elastic/apm/agent/bci/classloading/IndyPluginClassLoader.java:49]: We just looked at this together- the BB class loader makes specific use in this protection domain and the URLClassLoader uses the caller PD if it is not provided with an explicit one, which will be equivalent as passing the caller's PD.

File: elastic-apm-agent/src/main/java/co/elastic/apm/agent/premain/ShadedClassLoader.java [hunk 12]
```diff
@@ -196,34 +207,77 @@ private byte[] getShadedClassBytes(String name) throws ClassNotFoundException {
...
         }
-        return super.findResource(getShadedResourceName(name));
+
+        if (System.getSecurityManager() == null) {
+            return findResourceInternal(getShadedResourceName(name));
+        }
+
+        // while most of the body of default 'findResource' in JDK implementation is in a privileged action
+        // an extra URL check is performed just after it, hence we have to wrap the whole method call in a privileged
+        // action otherwise the security manager will complain about lack of proper read privileges on the agent jar
```
[the remark this answers is not in the document]
Comment (eyalkoren) [reply elastic-apm-agent/src/main/java/co/elastic/apm/agent/premain/ShadedClassLoader.java:247]: No need to pass a PD to the superclass. `URLClassLoader` would use the caller's PD by default if we don't which is equivalent.

**Review by eyalkoren — APPROVED** [review]
Only one more exception to avoid automatic casting in `AbstractJulEcsReformattingHelper`
