### PR TITLE
Fix ClassCastException on J9

### LINKED ISSUE #505: ClassCastException with adoptopenjdk/openjdk11-openj9
Hi

we upgrade to the current 1.4 version and got this error upon startup:

```
textPayload: "java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at co.elastic.apm.agent.bci.AgentMain.init(AgentMain.java:78)
	at co.elastic.apm.agent.bci.AgentMain.premain(AgentMain.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:191)
	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:180)
	at java.base/java.lang.Class.forNameImpl(Native Method)
	at java.base/java.lang.Class.forName(Class.java:340)
	at co.elastic.apm.agent.metrics.builtin.JvmGcMetrics.bindTo(JvmGcMetrics.java:66)
	at co.elastic.apm.agent.metrics.builtin.JvmGcMetrics.start(JvmGcMetrics.java:41)
	at co.elastic.apm.agent.impl.ElasticApmTracer.<init>(ElasticApmTracer.java:157)
	at co.elastic.apm.agent.impl.ElasticApmTracerBuilder.build(ElasticApmTracerBuilder.java:108)
	at co.elastic.apm.agent.bci.ElasticApmAgent.initialize(ElasticApmAgent.java:90)
	... 12 more
Caused by: java.lang.ClassCastException: com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl incompatible with com.sun.management.ThreadMXBean
	at co.elastic.apm.agent.metrics.builtin.JvmGcMetrics$HotspotAllocationSupplier.<init>(JvmGcMetrics.java:75)
	at co.elastic.apm.agent.metrics.builtin.JvmGcMetrics$HotspotAllocationSupplier.<clinit>(JvmGcMetrics.java:73)
```

For our project with have `adoptopenjdk/openjdk11-openj9` as base image. It seems that the given metric goes to much into VM specific details or should back-off if it does not find it.

### PR DESCRIPTION
**Pull request by felixbarny**
fixes #505

Snapshot: [elastic-apm-agent-1.4.1-SNAPSHOT.jar.zip](https://github.com/elastic/apm-agent-java/files/2919657/elastic-apm-agent-1.4.1-SNAPSHOT.jar.zip)

@remmeier could you try out the snapshot to verify that it actually fixes your problem?

### CODE REVIEW

**Comment by remmeier** [comment]
will need a moment to get a local (non maven repo) file into our builds

**Comment by remmeier** [comment]
looks good! thx for the super quick fix

File: apm-agent-core/src/main/java/co/elastic/apm/agent/metrics/builtin/JvmGcMetrics.java [hunk 1]
```diff
@@ -60,10 +60,12 @@ public double get() {
 
         try {
             // only refer to hotspot specific class via reflection to avoid linkage errors
-            Class.forName("com.sun.management.ThreadMXBean");
-            // in reference to JMH's GC profiler (gc.alloc.rate)
-            registry.add("jvm.gc.alloc", Collections.<String, String>emptyMap(),
-                (DoubleSupplier) Class.forName(getClass().getName() + "$HotspotAllocationSupplier").getEnumConstants()[0]);
+            final Class<?> sunBeanClass = Class.forName("com.sun.management.ThreadMXBean");
```
Comment (eyalkoren) [inline apm-agent-core/src/main/java/co/elastic/apm/agent/metrics/builtin/JvmGcMetrics.java]: Add 
```
// J9 does contain com.sun.management.ThreadMXBean in classpath , but the actual MBean it uses (com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl) does not implement it
```
